// Code generated by "stringer --type FeatureFlag internal/featureflags/featureflags.go"; DO NOT EDIT.

package featureflags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[placeholder-0]
	_ = x[DeployOTLPGateway-1]
}

const _FeatureFlag_name = "placeholderDeployOTLPGateway"

var _FeatureFlag_index = [...]uint8{0, 11, 28}

func (i FeatureFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FeatureFlag_index)-1 {
		return "FeatureFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeatureFlag_name[_FeatureFlag_index[idx]:_FeatureFlag_index[idx+1]]
}
