// Code generated by "stringer --type FeatureFlag internal/featureflags/featureflags.go"; DO NOT EDIT.

package featureflags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V1Beta1-0]
	_ = x[LogPipelineOTLP-1]
}

const _FeatureFlag_name = "V1Beta1LogPipelineOTLP"

var _FeatureFlag_index = [...]uint8{0, 7, 22}

func (i FeatureFlag) String() string {
	if i < 0 || i >= FeatureFlag(len(_FeatureFlag_index)-1) {
		return "FeatureFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeatureFlag_name[_FeatureFlag_index[i]:_FeatureFlag_index[i+1]]
}
