// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NewPipelineSyncer creates a new instance of PipelineSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPipelineSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PipelineSyncer {
	mock := &PipelineSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PipelineSyncer is an autogenerated mock type for the PipelineSyncer type
type PipelineSyncer struct {
	mock.Mock
}

type PipelineSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *PipelineSyncer) EXPECT() *PipelineSyncer_Expecter {
	return &PipelineSyncer_Expecter{mock: &_m.Mock}
}

// TryAcquireLock provides a mock function for the type PipelineSyncer
func (_mock *PipelineSyncer) TryAcquireLock(ctx context.Context, owner v1.Object) error {
	ret := _mock.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for TryAcquireLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.Object) error); ok {
		r0 = returnFunc(ctx, owner)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PipelineSyncer_TryAcquireLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryAcquireLock'
type PipelineSyncer_TryAcquireLock_Call struct {
	*mock.Call
}

// TryAcquireLock is a helper method to define mock.On call
//   - ctx
//   - owner
func (_e *PipelineSyncer_Expecter) TryAcquireLock(ctx interface{}, owner interface{}) *PipelineSyncer_TryAcquireLock_Call {
	return &PipelineSyncer_TryAcquireLock_Call{Call: _e.mock.On("TryAcquireLock", ctx, owner)}
}

func (_c *PipelineSyncer_TryAcquireLock_Call) Run(run func(ctx context.Context, owner v1.Object)) *PipelineSyncer_TryAcquireLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.Object))
	})
	return _c
}

func (_c *PipelineSyncer_TryAcquireLock_Call) Return(err error) *PipelineSyncer_TryAcquireLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PipelineSyncer_TryAcquireLock_Call) RunAndReturn(run func(ctx context.Context, owner v1.Object) error) *PipelineSyncer_TryAcquireLock_Call {
	_c.Call.Return(run)
	return _c
}
