{
 "title": "Kyma / Telemetry / Fluent Bit",
 "description": "Inspired by https://grafana.com/grafana/dashboards/7752",
 "tags": [
  "kyma",
  "telemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{pod=~\".*telemetry-fluent-bit.*\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*telemetry-fluent-bit.*\"})",
     "legendFormat": "Active Fluent-bit"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Ready Nodes"
    },
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\"})",
     "legendFormat": "Non-Ready Nodes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "telemetry_unsupported_logpipelines{service=\"telemetry-operator-metrics\"}"
    }
   ]
  },
  { "title": "FluentBit metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Input Bytes Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{pod=~\"$pod\"}[5m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{pod=~\"$pod\"}[5m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{pod=~\"$pod\"}[5m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod=~\"$pod\"}[5m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{pod=~\"$pod\"}[1m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }} Retries to {{ name }}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{pod=~\"$pod\"}[1m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }} Failed Retries to {{ name }}"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "errors/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{pod=~\"$pod\"}[1m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Filter Drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_drop_records_total{pod=~\"$pod\"}[5m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }} / {{ name }}"
    }
   ]
  },
  {
   "title": "Filter Add",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_add_records_total{pod=~\"$pod\"}[5m])) by (pod, instance, name)",
     "legendFormat": "{{ pod }} / {{ name }}"
    }
   ]
  },
  {
   "title": "Filesystem Buffer Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "telemetry_fsbuffer_usage_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} - {{ directory }}"
    }
   ]
  },
  {
   "title": "Open/Closed/Rotated Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(fluentbit_input_files_opened_total{pod=~\"$pod\"}[1m])",
     "legendFormat": "Opened Files - {{ pod }}"
    },
    {
     "expr": "increase(fluentbit_input_files_closed_total{pod=~\"$pod\"}[1m])",
     "legendFormat": "Closed Files - {{ pod }}"
    },
    {
     "expr": "increase(fluentbit_input_files_rotated_total{pod=~\"$pod\"}[1m])",
     "legendFormat": "Rotated Files - {{ pod }}"
    }
   ]
  },
  { "title": "Kubernetes metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\", container!=\"POD\", container!=\"\"}\n",
     "legendFormat": "{{ container }} - {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{ pod }} limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod\",container!=\"POD\",container!=\"\"}) by (container, pod)",
     "legendFormat": "{{ container }} - {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{ pod }} limits"
    }
   ]
  }
 ]
}