{
 "title": "Kyma / Telemetry / Trace Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [
  "kyma",
  "telemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "receiver", "label": "receiver", "query": { "query": "label_values(receiver)" } },
   { "name": "exporter", "label": "exporter", "query": { "query": "label_values(exporter)" } },
   { "name": "processor", "label": "processor", "query": { "query": "label_values(processor)" } }
  ]
 },
 "panels": [
  {
   "title": "Receivers / Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "graph",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  {
   "title": "Processor Spans Received, Dropped, Accepted, Refused/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_received_spans{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | received"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "graph",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed /sec"
    }
   ]
  },
  {
   "title": "Queued Retry Max Queue / Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_capacity)",
     "legendFormat": "Queue Capacity"
    },
    {
     "expr": "max(otelcol_exporter_queue_size)",
     "legendFormat": "Queue Size"
    }
   ]
  },
  {
   "title": "QueuedRetry Successful vs Failed Sent/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent spans"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} failed spans"
    }
   ]
  }
 ]
}