// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	cert "github.com/kyma-project/telemetry-manager/internal/tls/cert"

	mock "github.com/stretchr/testify/mock"
)

// TLSCertValidator is an autogenerated mock type for the TLSCertValidator type
type TLSCertValidator struct {
	mock.Mock
}

// ValidateCertificate provides a mock function with given fields: certPEM, keyPEM
func (_m *TLSCertValidator) ValidateCertificate(certPEM []byte, keyPEM []byte) cert.TLSCertValidationResult {
	ret := _m.Called(certPEM, keyPEM)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCertificate")
	}

	var r0 cert.TLSCertValidationResult
	if rf, ok := ret.Get(0).(func([]byte, []byte) cert.TLSCertValidationResult); ok {
		r0 = rf(certPEM, keyPEM)
	} else {
		r0 = ret.Get(0).(cert.TLSCertValidationResult)
	}

	return r0
}

// NewTLSCertValidator creates a new instance of TLSCertValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTLSCertValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TLSCertValidator {
	mock := &TLSCertValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
