package names

const (
	telemetryPrefix       = "telemetry-"
	metricsSuffix         = "-metrics"
	exporterMetricsSuffix = "-exporter-metrics" // used for Fluent Bit directory-size exporter

	LogAgent      = telemetryPrefix + "log-agent"
	MetricAgent   = telemetryPrefix + "metric-agent"
	LogGateway    = telemetryPrefix + "log-gateway"
	MetricGateway = telemetryPrefix + "metric-gateway"
	TraceGateway  = telemetryPrefix + "trace-gateway"
	OTLPGateway   = telemetryPrefix + "otlp-gateway"

	LogAgentMetricsService      = LogAgent + metricsSuffix
	MetricAgentMetricsService   = MetricAgent + metricsSuffix
	LogGatewayMetricsService    = LogGateway + metricsSuffix
	MetricGatewayMetricsService = MetricGateway + metricsSuffix
	TraceGatewayMetricsService  = TraceGateway + metricsSuffix

	FluentBit                       = telemetryPrefix + "fluent-bit"
	FluentBitMetricsService         = FluentBit + metricsSuffix
	FluentBitExporterMetricsService = FluentBit + exporterMetricsSuffix
	FluentBitSectionsConfigMap      = FluentBit + "-sections"
	FluentBitFilesConfigMap         = FluentBit + "-files"
	FluentBitLuaScriptsConfigMap    = FluentBit + "-luascripts"
	FluentBitParsersConfigMap       = FluentBit + "-parsers"
	FluentBitEnvSecret              = FluentBit + "-env"
	FluentBitTLSConfigSecret        = FluentBit + "-output-tls-config"

	OTLPMetricsService = telemetryPrefix + "otlp-metrics"
	OTLPTracesService  = telemetryPrefix + "otlp-traces"
	OTLPLogsService    = telemetryPrefix + "otlp-logs"
	OTLPService        = telemetryPrefix + "otlp-gateway"

	SelfMonitor = telemetryPrefix + "self-monitor"

	ManagerLeaseName         = "cdd7ef0b.kyma-project.io" // generated by kubebuilder, must not be changed
	ManagerMetricsService    = telemetryPrefix + "manager-metrics"
	ManagerWebhookService    = telemetryPrefix + "manager-webhook"
	ManagerWebhookCertSecret = telemetryPrefix + "webhook-cert"
	ValidatingWebhookConfig  = telemetryPrefix + "validating-webhook.kyma-project.io"
	MutatingWebhookConfig    = telemetryPrefix + "mutating-webhook.kyma-project.io"

	LogPipelineLock    = telemetryPrefix + "logpipeline-lock"
	LogPipelineSync    = telemetryPrefix + "logpipeline-sync"
	MetricPipelineLock = telemetryPrefix + "metricpipeline-lock"
	MetricPipelineSync = telemetryPrefix + "metricpipeline-sync"
	TracePipelineLock  = telemetryPrefix + "tracepipeline-lock"
	TracePipelineSync  = telemetryPrefix + "tracepipeline-sync"

	OverrideConfigMap = telemetryPrefix + "override-config"
	DefaultTelemetry  = "default" // default module resource must be named "default"

	LogPipelineCRD    = "logpipelines.telemetry.kyma-project.io"
	MetricPipelineCRD = "metricpipelines.telemetry.kyma-project.io"
)

// MetricsServiceName returns the metrics service name for a given component name
func MetricsServiceName(componentName string) string {
	return componentName + metricsSuffix
}
