module-name: telemetry
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:1.62.0
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20260413-7d161633
  - europe-docker.pkg.dev/kyma-project/prod/external/fluent/fluent-bit:4.2.3
  - europe-docker.pkg.dev/kyma-project/prod/kyma-otel-collector:0.149.0-1.62.0
  - europe-docker.pkg.dev/kyma-project/prod/tpi/telemetry-self-monitor:v20260311-e32d5d84
  - europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/prometheus-fips:3.10.0
  - europe-docker.pkg.dev/kyma-project/prod/external/library/alpine:3.23.3
mend:
  language: golang-mod
  exclude:
    - '**/mocks/**'
    - '**/stubs/**'
    - '**/test/**'
    - '**/*_test.go'
    - docs/**
    - dependencies/populateimages/**
    - dependencies/sample-app/**
    - dependencies/stdout-log-generator/**
    - dependencies/fault-backend/**
    - internal/tools/**
    - apis/telemetry/v1alpha1/zz_generated.conversion.go
checkmarx-one:
  preset: go-default
  exclude:
    - '**/mocks/**'
    - '**/stubs/**'
    - '**/test/**'
    - '**/*_test.go'
    - docs/**
    - dependencies/populateimages/**
    - dependencies/sample-app/**
    - dependencies/stdout-log-generator/**
    - dependencies/fault-backend/**
    - internal/tools/**
    - apis/telemetry/v1alpha1/zz_generated.conversion.go
