module-name: telemetry
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:1.64.0
  - europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20260510-6593fbfb
  - europe-docker.pkg.dev/kyma-project/prod/external/fluent/fluent-bit:5.0.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-otel-collector:0.152.1-1.64.0
  - europe-docker.pkg.dev/kyma-project/prod/tpi/telemetry-self-monitor:v20260430-87ba5cf7
  - europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/prometheus-fips:3.11.3
  - europe-docker.pkg.dev/kyma-project/prod/external/library/alpine:3.23.4
mend:
  language: golang-mod
  exclude:
    - '**/mocks/**'
    - '**/stubs/**'
    - '**/test/**'
    - '**/*_test.go'
    - docs/**
    - dependencies/populateimages/**
    - dependencies/sample-app/**
    - dependencies/stdout-log-generator/**
    - dependencies/fault-backend/**
    - internal/tools/**
    - apis/telemetry/v1alpha1/zz_generated.conversion.go
checkmarx-one:
  preset: go-default
  exclude:
    - '**/mocks/**'
    - '**/stubs/**'
    - '**/test/**'
    - '**/*_test.go'
    - docs/**
    - dependencies/populateimages/**
    - dependencies/sample-app/**
    - dependencies/stdout-log-generator/**
    - dependencies/fault-backend/**
    - internal/tools/**
    - apis/telemetry/v1alpha1/zz_generated.conversion.go
