// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"

	selfmonitor "github.com/kyma-project/telemetry-manager/internal/resources/selfmonitor"
)

// SelfMonitorApplierDeleter is an autogenerated mock type for the SelfMonitorApplierDeleter type
type SelfMonitorApplierDeleter struct {
	mock.Mock
}

// ApplyResources provides a mock function with given fields: ctx, c, opts
func (_m *SelfMonitorApplierDeleter) ApplyResources(ctx context.Context, c client.Client, opts selfmonitor.ApplyOptions) error {
	ret := _m.Called(ctx, c, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Client, selfmonitor.ApplyOptions) error); ok {
		r0 = rf(ctx, c, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteResources provides a mock function with given fields: ctx, c
func (_m *SelfMonitorApplierDeleter) DeleteResources(ctx context.Context, c client.Client) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Client) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSelfMonitorApplierDeleter creates a new instance of SelfMonitorApplierDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSelfMonitorApplierDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SelfMonitorApplierDeleter {
	mock := &SelfMonitorApplierDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
