apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-logpipelines
  namespace: {{ .Release.Namespace }}
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
  {{- include "telemetry-manager.labels" . | nindent 4 }}
data: {{ .Files.Get "files/logpipelines-busola-config.yaml" | nindent 2 }}