apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-manager-metrics
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "telemetry-manager.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
  {{- include "telemetry-manager.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.managerMetrics.ports | toYaml | nindent 2 }}
