apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-manager-webhook
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "telemetry-manager.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "telemetry-manager.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.managerWebhook.ports | toYaml | nindent 2 }}
