apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-priority-class
  labels:
  {{- include "telemetry-manager.labels" . | nindent 4 }}
description: Global (default) scheduling priority of Kyma components. Must not be
  blocked by unschedulable user workloads.
globalDefault: false
value: 2000000
