apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-manager
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "telemetry-manager.labels" . | nindent 4 }}