// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/kyma-project/telemetry-manager/apis/telemetry/v1alpha1"
)

// FileWriter is an autogenerated mock type for the fileWriter type
type FileWriter struct {
	mock.Mock
}

// PrepareParserDryRun provides a mock function with given fields: ctx, workDir, pipeline
func (_m *FileWriter) PrepareParserDryRun(ctx context.Context, workDir string, pipeline *v1alpha1.LogParser) (func(), error) {
	ret := _m.Called(ctx, workDir, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for PrepareParserDryRun")
	}

	var r0 func()
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.LogParser) (func(), error)); ok {
		return rf(ctx, workDir, pipeline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.LogParser) func()); ok {
		r0 = rf(ctx, workDir, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.LogParser) error); ok {
		r1 = rf(ctx, workDir, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreparePipelineDryRun provides a mock function with given fields: ctx, workDir, pipeline
func (_m *FileWriter) PreparePipelineDryRun(ctx context.Context, workDir string, pipeline *v1alpha1.LogPipeline) (func(), error) {
	ret := _m.Called(ctx, workDir, pipeline)

	if len(ret) == 0 {
		panic("no return value specified for PreparePipelineDryRun")
	}

	var r0 func()
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.LogPipeline) (func(), error)); ok {
		return rf(ctx, workDir, pipeline)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.LogPipeline) func()); ok {
		r0 = rf(ctx, workDir, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.LogPipeline) error); ok {
		r1 = rf(ctx, workDir, pipeline)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileWriter creates a new instance of FileWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileWriter {
	mock := &FileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
