opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false

default:
  envOverrides:
  - name: OTEL_SERVICE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: "metadata.labels['app.kubernetes.io/name']"
  - name: OTEL_COLLECTOR_NAME
    value: telemetry-otlp.kyma-system

components:
  accounting:
    enabled: true
    podAnnotations:
      oneagent.dynatrace.com/inject: "false" # Seem to not work with .NET
    resources:
      requests:
        memory: 150Mi
      limits:
        memory: 300Mi

  ad:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 350Mi
      limits:
        memory: 500Mi

  cart:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 150Mi
      limits:
        memory: 200Mi

  checkout:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi

  currency:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi

  email:
    enabled: true
    service:
      port: null
    ports:
      - name: http
        value: 8080
    resources:
      requests:
        memory: 140Mi
      limits:
        memory: 150Mi

  fraud-detection:
    enabled: true
    resources:
      requests:
        memory: 400Mi
      limits:
        memory: 700Mi

  frontend:
    enabled: true
    service:
      port: null
    ports:
      - name: http
        value: 8080
    resources:
      requests:
        memory: 300Mi
      limits:
        memory: 500Mi
    podAnnotations:
      traffic.sidecar.istio.io/excludeInboundPorts: "8080"

  frontend-proxy:
    enabled: true
    service:
      port: null
    ports:
      - name: http
        value: 8080
    resources:
      requests:
        memory: 80Mi
      limits:
        memory: 150Mi
    podAnnotations:
      sidecar.istio.io/inject: "false"
    
  image-provider:
    enabled: true
    service:
      port: null
    ports:
      - name: http
        value: 8081
    resources:
      requests:
        memory: 50Mi
      limits:
        memory: 150Mi
    podAnnotations:
      sidecar.istio.io/inject: "false"

  llm:
    enabled: true
    resources:
      requests:
        memory: 150Mi
      limits:
        memory: 200Mi

  load-generator:
    enabled: true
    envOverrides:
      - name: LOCUST_USERS
        value: '2'
    service:
      port: null
    ports:
      - name: http
        value: 8089
    resources:
      requests:
        memory: 300Mi
      limits:
        memory: 2500Mi
    podAnnotations:
      sidecar.istio.io/inject: "false"

  payment:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 250Mi
      limits:
        memory: 350Mi

  postgresql:
    enabled: true
    resources:
      limits:
        memory: 200Mi

  product-catalog:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 120Mi
      limits:
        memory: 200Mi

  product-reviews:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 3551
    resources:
      requests:
        memory: 150Mi
      limits:
        memory: 200Mi

  quote:
    enabled: true
    service:
      port: null
    ports:
      - name: http
        value: 8080
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi

  recommendation:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 120Mi
      limits:
        memory: 200Mi

  shipping:
    enabled: true
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi

  flagd:
    enabled: true
    resources:
      requests:
        memory: 240Mi
      limits:
        memory: 400Mi
    podAnnotations:
      sidecar.istio.io/inject: "false"

  kafka:
    enabled: true
    resources:
      requests:
        memory: 500Mi
      limits:
        memory: 800Mi

  valkey-cart:
    enabled: true
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi
