// Code generated by "stringer --type Mode internal/utils/logpipeline/logpipeline.go"; DO NOT EDIT.

package logpipeline

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTel-0]
	_ = x[FluentBit-1]
}

const _Mode_name = "OTelFluentBit"

var _Mode_index = [...]uint8{0, 4, 13}

func (i Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
