// Code generated by "stringer --type LogMode internal/utils/pipelines/log_mode.go"; DO NOT EDIT.

package logpipeline

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTel-0]
	_ = x[FluentBit-1]
}

const _LogMode_name = "OTelFluentBit"

var _LogMode_index = [...]uint8{0, 4, 13}

func (i LogMode) String() string {
	if i < 0 || i >= LogMode(len(_LogMode_index)-1) {
		return "LogMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogMode_name[_LogMode_index[i]:_LogMode_index[i+1]]
}
