// Code generated by "stringer --type LogPipelineMode internal/utils/pipelines/logpipeline.go"; DO NOT EDIT.

package pipelines

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTel-0]
	_ = x[FluentBit-1]
}

const _LogPipelineMode_name = "OTelFluentBit"

var _LogPipelineMode_index = [...]uint8{0, 4, 13}

func (i LogPipelineMode) String() string {
	if i < 0 || i >= LogPipelineMode(len(_LogPipelineMode_index)-1) {
		return "LogPipelineMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogPipelineMode_name[_LogPipelineMode_index[i]:_LogPipelineMode_index[i+1]]
}
