// This file is generated by "make generate".
// Don't edit, update .env file and run make target generate.

package testkit

const (
	DefaultTelemetryGenImage  = "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.139.0"
	DefaultOTelCollectorContribImage = "otel/opentelemetry-collector-contrib:0.139.0"
	DefaultOTelCollectorImage = "europe-docker.pkg.dev/kyma-project/prod/kyma-otel-collector:0.139.0-main"
)
