//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/kyma-project/telemetry-manager/apis/telemetry/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AuthenticationOptions)(nil), (*v1beta1.AuthenticationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationOptions_To_v1beta1_AuthenticationOptions(a.(*AuthenticationOptions), b.(*v1beta1.AuthenticationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.AuthenticationOptions)(nil), (*AuthenticationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AuthenticationOptions_To_v1alpha1_AuthenticationOptions(a.(*v1beta1.AuthenticationOptions), b.(*AuthenticationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BasicAuthOptions)(nil), (*v1beta1.BasicAuthOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BasicAuthOptions_To_v1beta1_BasicAuthOptions(a.(*BasicAuthOptions), b.(*v1beta1.BasicAuthOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BasicAuthOptions)(nil), (*BasicAuthOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BasicAuthOptions_To_v1alpha1_BasicAuthOptions(a.(*v1beta1.BasicAuthOptions), b.(*BasicAuthOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvoyMetrics)(nil), (*v1beta1.EnvoyMetrics)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnvoyMetrics_To_v1beta1_EnvoyMetrics(a.(*EnvoyMetrics), b.(*v1beta1.EnvoyMetrics), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EnvoyMetrics)(nil), (*EnvoyMetrics)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EnvoyMetrics_To_v1alpha1_EnvoyMetrics(a.(*v1beta1.EnvoyMetrics), b.(*EnvoyMetrics), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FilterSpec)(nil), (*v1beta1.FilterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FilterSpec_To_v1beta1_FilterSpec(a.(*FilterSpec), b.(*v1beta1.FilterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FilterSpec)(nil), (*FilterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FilterSpec_To_v1alpha1_FilterSpec(a.(*v1beta1.FilterSpec), b.(*FilterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FluentBitFile)(nil), (*v1beta1.FluentBitFile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FluentBitFile_To_v1beta1_FluentBitFile(a.(*FluentBitFile), b.(*v1beta1.FluentBitFile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FluentBitFile)(nil), (*FluentBitFile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FluentBitFile_To_v1alpha1_FluentBitFile(a.(*v1beta1.FluentBitFile), b.(*FluentBitFile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FluentBitFilter)(nil), (*v1beta1.FluentBitFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FluentBitFilter_To_v1beta1_FluentBitFilter(a.(*FluentBitFilter), b.(*v1beta1.FluentBitFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FluentBitFilter)(nil), (*FluentBitFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FluentBitFilter_To_v1alpha1_FluentBitFilter(a.(*v1beta1.FluentBitFilter), b.(*FluentBitFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FluentBitHTTPOutput)(nil), (*v1beta1.FluentBitHTTPOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FluentBitHTTPOutput_To_v1beta1_FluentBitHTTPOutput(a.(*FluentBitHTTPOutput), b.(*v1beta1.FluentBitHTTPOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FluentBitHTTPOutput)(nil), (*FluentBitHTTPOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FluentBitHTTPOutput_To_v1alpha1_FluentBitHTTPOutput(a.(*v1beta1.FluentBitHTTPOutput), b.(*FluentBitHTTPOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FluentBitVariable)(nil), (*v1beta1.FluentBitVariable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FluentBitVariable_To_v1beta1_FluentBitVariable(a.(*FluentBitVariable), b.(*v1beta1.FluentBitVariable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FluentBitVariable)(nil), (*FluentBitVariable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FluentBitVariable_To_v1alpha1_FluentBitVariable(a.(*v1beta1.FluentBitVariable), b.(*FluentBitVariable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Header)(nil), (*v1beta1.Header)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Header_To_v1beta1_Header(a.(*Header), b.(*v1beta1.Header), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Header)(nil), (*Header)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Header_To_v1alpha1_Header(a.(*v1beta1.Header), b.(*Header), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogPipeline)(nil), (*v1beta1.LogPipeline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipeline_To_v1beta1_LogPipeline(a.(*LogPipeline), b.(*v1beta1.LogPipeline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LogPipeline)(nil), (*LogPipeline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipeline_To_v1alpha1_LogPipeline(a.(*v1beta1.LogPipeline), b.(*LogPipeline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogPipelineContainerSelector)(nil), (*v1beta1.LogPipelineContainerSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipelineContainerSelector_To_v1beta1_LogPipelineContainerSelector(a.(*LogPipelineContainerSelector), b.(*v1beta1.LogPipelineContainerSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LogPipelineContainerSelector)(nil), (*LogPipelineContainerSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipelineContainerSelector_To_v1alpha1_LogPipelineContainerSelector(a.(*v1beta1.LogPipelineContainerSelector), b.(*LogPipelineContainerSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogPipelineList)(nil), (*v1beta1.LogPipelineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipelineList_To_v1beta1_LogPipelineList(a.(*LogPipelineList), b.(*v1beta1.LogPipelineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LogPipelineList)(nil), (*LogPipelineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipelineList_To_v1alpha1_LogPipelineList(a.(*v1beta1.LogPipelineList), b.(*LogPipelineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogPipelineOutput)(nil), (*v1beta1.LogPipelineOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipelineOutput_To_v1beta1_LogPipelineOutput(a.(*LogPipelineOutput), b.(*v1beta1.LogPipelineOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LogPipelineOutput)(nil), (*LogPipelineOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipelineOutput_To_v1alpha1_LogPipelineOutput(a.(*v1beta1.LogPipelineOutput), b.(*LogPipelineOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogPipelineSpec)(nil), (*v1beta1.LogPipelineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipelineSpec_To_v1beta1_LogPipelineSpec(a.(*LogPipelineSpec), b.(*v1beta1.LogPipelineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LogPipelineSpec)(nil), (*LogPipelineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipelineSpec_To_v1alpha1_LogPipelineSpec(a.(*v1beta1.LogPipelineSpec), b.(*LogPipelineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LogPipelineStatus)(nil), (*v1beta1.LogPipelineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipelineStatus_To_v1beta1_LogPipelineStatus(a.(*LogPipelineStatus), b.(*v1beta1.LogPipelineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LogPipelineStatus)(nil), (*LogPipelineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipelineStatus_To_v1alpha1_LogPipelineStatus(a.(*v1beta1.LogPipelineStatus), b.(*LogPipelineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipeline)(nil), (*v1beta1.MetricPipeline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipeline_To_v1beta1_MetricPipeline(a.(*MetricPipeline), b.(*v1beta1.MetricPipeline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipeline)(nil), (*MetricPipeline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipeline_To_v1alpha1_MetricPipeline(a.(*v1beta1.MetricPipeline), b.(*MetricPipeline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineInput)(nil), (*v1beta1.MetricPipelineInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineInput_To_v1beta1_MetricPipelineInput(a.(*MetricPipelineInput), b.(*v1beta1.MetricPipelineInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineInput)(nil), (*MetricPipelineInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineInput_To_v1alpha1_MetricPipelineInput(a.(*v1beta1.MetricPipelineInput), b.(*MetricPipelineInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineIstioInput)(nil), (*v1beta1.MetricPipelineIstioInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineIstioInput_To_v1beta1_MetricPipelineIstioInput(a.(*MetricPipelineIstioInput), b.(*v1beta1.MetricPipelineIstioInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineIstioInput)(nil), (*MetricPipelineIstioInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineIstioInput_To_v1alpha1_MetricPipelineIstioInput(a.(*v1beta1.MetricPipelineIstioInput), b.(*MetricPipelineIstioInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineIstioInputDiagnosticMetrics)(nil), (*v1beta1.MetricPipelineIstioInputDiagnosticMetrics)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics_To_v1beta1_MetricPipelineIstioInputDiagnosticMetrics(a.(*MetricPipelineIstioInputDiagnosticMetrics), b.(*v1beta1.MetricPipelineIstioInputDiagnosticMetrics), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineIstioInputDiagnosticMetrics)(nil), (*MetricPipelineIstioInputDiagnosticMetrics)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineIstioInputDiagnosticMetrics_To_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics(a.(*v1beta1.MetricPipelineIstioInputDiagnosticMetrics), b.(*MetricPipelineIstioInputDiagnosticMetrics), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineList)(nil), (*v1beta1.MetricPipelineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineList_To_v1beta1_MetricPipelineList(a.(*MetricPipelineList), b.(*v1beta1.MetricPipelineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineList)(nil), (*MetricPipelineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineList_To_v1alpha1_MetricPipelineList(a.(*v1beta1.MetricPipelineList), b.(*MetricPipelineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineOutput)(nil), (*v1beta1.MetricPipelineOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineOutput_To_v1beta1_MetricPipelineOutput(a.(*MetricPipelineOutput), b.(*v1beta1.MetricPipelineOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineOutput)(nil), (*MetricPipelineOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineOutput_To_v1alpha1_MetricPipelineOutput(a.(*v1beta1.MetricPipelineOutput), b.(*MetricPipelineOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelinePrometheusInput)(nil), (*v1beta1.MetricPipelinePrometheusInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelinePrometheusInput_To_v1beta1_MetricPipelinePrometheusInput(a.(*MetricPipelinePrometheusInput), b.(*v1beta1.MetricPipelinePrometheusInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelinePrometheusInput)(nil), (*MetricPipelinePrometheusInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelinePrometheusInput_To_v1alpha1_MetricPipelinePrometheusInput(a.(*v1beta1.MetricPipelinePrometheusInput), b.(*MetricPipelinePrometheusInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineRuntimeInput)(nil), (*MetricPipelineRuntimeInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineRuntimeInput_To_v1alpha1_MetricPipelineRuntimeInput(a.(*v1beta1.MetricPipelineRuntimeInput), b.(*MetricPipelineRuntimeInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineRuntimeInputResource)(nil), (*v1beta1.MetricPipelineRuntimeInputResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineRuntimeInputResource_To_v1beta1_MetricPipelineRuntimeInputResource(a.(*MetricPipelineRuntimeInputResource), b.(*v1beta1.MetricPipelineRuntimeInputResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineRuntimeInputResource)(nil), (*MetricPipelineRuntimeInputResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineRuntimeInputResource_To_v1alpha1_MetricPipelineRuntimeInputResource(a.(*v1beta1.MetricPipelineRuntimeInputResource), b.(*MetricPipelineRuntimeInputResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineRuntimeInputResources)(nil), (*v1beta1.MetricPipelineRuntimeInputResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineRuntimeInputResources_To_v1beta1_MetricPipelineRuntimeInputResources(a.(*MetricPipelineRuntimeInputResources), b.(*v1beta1.MetricPipelineRuntimeInputResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineRuntimeInputResources)(nil), (*MetricPipelineRuntimeInputResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineRuntimeInputResources_To_v1alpha1_MetricPipelineRuntimeInputResources(a.(*v1beta1.MetricPipelineRuntimeInputResources), b.(*MetricPipelineRuntimeInputResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineSpec)(nil), (*v1beta1.MetricPipelineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineSpec_To_v1beta1_MetricPipelineSpec(a.(*MetricPipelineSpec), b.(*v1beta1.MetricPipelineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineSpec)(nil), (*MetricPipelineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineSpec_To_v1alpha1_MetricPipelineSpec(a.(*v1beta1.MetricPipelineSpec), b.(*MetricPipelineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetricPipelineStatus)(nil), (*v1beta1.MetricPipelineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineStatus_To_v1beta1_MetricPipelineStatus(a.(*MetricPipelineStatus), b.(*v1beta1.MetricPipelineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MetricPipelineStatus)(nil), (*MetricPipelineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MetricPipelineStatus_To_v1alpha1_MetricPipelineStatus(a.(*v1beta1.MetricPipelineStatus), b.(*MetricPipelineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceSelector)(nil), (*v1beta1.NamespaceSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NamespaceSelector_To_v1beta1_NamespaceSelector(a.(*NamespaceSelector), b.(*v1beta1.NamespaceSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NamespaceSelector)(nil), (*NamespaceSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NamespaceSelector_To_v1alpha1_NamespaceSelector(a.(*v1beta1.NamespaceSelector), b.(*NamespaceSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OAuth2Options)(nil), (*v1beta1.OAuth2Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OAuth2Options_To_v1beta1_OAuth2Options(a.(*OAuth2Options), b.(*v1beta1.OAuth2Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OAuth2Options)(nil), (*OAuth2Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OAuth2Options_To_v1alpha1_OAuth2Options(a.(*v1beta1.OAuth2Options), b.(*OAuth2Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OTLPOutput)(nil), (*v1beta1.OTLPOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OTLPOutput_To_v1beta1_OTLPOutput(a.(*OTLPOutput), b.(*v1beta1.OTLPOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.OTLPOutput)(nil), (*OTLPOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OTLPOutput_To_v1alpha1_OTLPOutput(a.(*v1beta1.OTLPOutput), b.(*OTLPOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretKeyRef)(nil), (*v1beta1.SecretKeyRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretKeyRef_To_v1beta1_SecretKeyRef(a.(*SecretKeyRef), b.(*v1beta1.SecretKeyRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.SecretKeyRef)(nil), (*SecretKeyRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretKeyRef_To_v1alpha1_SecretKeyRef(a.(*v1beta1.SecretKeyRef), b.(*SecretKeyRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TracePipeline)(nil), (*v1beta1.TracePipeline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TracePipeline_To_v1beta1_TracePipeline(a.(*TracePipeline), b.(*v1beta1.TracePipeline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TracePipeline)(nil), (*TracePipeline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TracePipeline_To_v1alpha1_TracePipeline(a.(*v1beta1.TracePipeline), b.(*TracePipeline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TracePipelineList)(nil), (*v1beta1.TracePipelineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TracePipelineList_To_v1beta1_TracePipelineList(a.(*TracePipelineList), b.(*v1beta1.TracePipelineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TracePipelineList)(nil), (*TracePipelineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TracePipelineList_To_v1alpha1_TracePipelineList(a.(*v1beta1.TracePipelineList), b.(*TracePipelineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TracePipelineOutput)(nil), (*v1beta1.TracePipelineOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TracePipelineOutput_To_v1beta1_TracePipelineOutput(a.(*TracePipelineOutput), b.(*v1beta1.TracePipelineOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TracePipelineOutput)(nil), (*TracePipelineOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TracePipelineOutput_To_v1alpha1_TracePipelineOutput(a.(*v1beta1.TracePipelineOutput), b.(*TracePipelineOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TracePipelineSpec)(nil), (*v1beta1.TracePipelineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TracePipelineSpec_To_v1beta1_TracePipelineSpec(a.(*TracePipelineSpec), b.(*v1beta1.TracePipelineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TracePipelineSpec)(nil), (*TracePipelineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TracePipelineSpec_To_v1alpha1_TracePipelineSpec(a.(*v1beta1.TracePipelineSpec), b.(*TracePipelineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TracePipelineStatus)(nil), (*v1beta1.TracePipelineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TracePipelineStatus_To_v1beta1_TracePipelineStatus(a.(*TracePipelineStatus), b.(*v1beta1.TracePipelineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TracePipelineStatus)(nil), (*TracePipelineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TracePipelineStatus_To_v1alpha1_TracePipelineStatus(a.(*v1beta1.TracePipelineStatus), b.(*TracePipelineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TransformSpec)(nil), (*v1beta1.TransformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TransformSpec_To_v1beta1_TransformSpec(a.(*TransformSpec), b.(*v1beta1.TransformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TransformSpec)(nil), (*TransformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TransformSpec_To_v1alpha1_TransformSpec(a.(*v1beta1.TransformSpec), b.(*TransformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValueFromSource)(nil), (*v1beta1.ValueFromSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValueFromSource_To_v1beta1_ValueFromSource(a.(*ValueFromSource), b.(*v1beta1.ValueFromSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ValueFromSource)(nil), (*ValueFromSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ValueFromSource_To_v1alpha1_ValueFromSource(a.(*v1beta1.ValueFromSource), b.(*ValueFromSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValueType)(nil), (*v1beta1.ValueType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValueType_To_v1beta1_ValueType(a.(*ValueType), b.(*v1beta1.ValueType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ValueType)(nil), (*ValueType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ValueType_To_v1alpha1_ValueType(a.(*v1beta1.ValueType), b.(*ValueType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*FluentBitHTTPOutputTLS)(nil), (*v1beta1.OutputTLS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FluentBitHTTPOutputTLS_To_v1beta1_OutputTLS(a.(*FluentBitHTTPOutputTLS), b.(*v1beta1.OutputTLS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*LogPipelineInput)(nil), (*v1beta1.LogPipelineInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LogPipelineInput_To_v1beta1_LogPipelineInput(a.(*LogPipelineInput), b.(*v1beta1.LogPipelineInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*MetricPipelineRuntimeInput)(nil), (*v1beta1.MetricPipelineRuntimeInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetricPipelineRuntimeInput_To_v1beta1_MetricPipelineRuntimeInput(a.(*MetricPipelineRuntimeInput), b.(*v1beta1.MetricPipelineRuntimeInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*OTLPInput)(nil), (*v1beta1.OTLPInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OTLPInput_To_v1beta1_OTLPInput(a.(*OTLPInput), b.(*v1beta1.OTLPInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.LogPipelineInput)(nil), (*LogPipelineInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LogPipelineInput_To_v1alpha1_LogPipelineInput(a.(*v1beta1.LogPipelineInput), b.(*LogPipelineInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.OTLPInput)(nil), (*OTLPInput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OTLPInput_To_v1alpha1_OTLPInput(a.(*v1beta1.OTLPInput), b.(*OTLPInput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.OutputTLS)(nil), (*FluentBitHTTPOutputTLS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OutputTLS_To_v1alpha1_FluentBitHTTPOutputTLS(a.(*v1beta1.OutputTLS), b.(*FluentBitHTTPOutputTLS), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuthenticationOptions_To_v1beta1_AuthenticationOptions(in *AuthenticationOptions, out *v1beta1.AuthenticationOptions, s conversion.Scope) error {
	out.Basic = (*v1beta1.BasicAuthOptions)(unsafe.Pointer(in.Basic))
	out.OAuth2 = (*v1beta1.OAuth2Options)(unsafe.Pointer(in.OAuth2))
	return nil
}

// Convert_v1alpha1_AuthenticationOptions_To_v1beta1_AuthenticationOptions is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationOptions_To_v1beta1_AuthenticationOptions(in *AuthenticationOptions, out *v1beta1.AuthenticationOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationOptions_To_v1beta1_AuthenticationOptions(in, out, s)
}

func autoConvert_v1beta1_AuthenticationOptions_To_v1alpha1_AuthenticationOptions(in *v1beta1.AuthenticationOptions, out *AuthenticationOptions, s conversion.Scope) error {
	out.Basic = (*BasicAuthOptions)(unsafe.Pointer(in.Basic))
	out.OAuth2 = (*OAuth2Options)(unsafe.Pointer(in.OAuth2))
	return nil
}

// Convert_v1beta1_AuthenticationOptions_To_v1alpha1_AuthenticationOptions is an autogenerated conversion function.
func Convert_v1beta1_AuthenticationOptions_To_v1alpha1_AuthenticationOptions(in *v1beta1.AuthenticationOptions, out *AuthenticationOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_AuthenticationOptions_To_v1alpha1_AuthenticationOptions(in, out, s)
}

func autoConvert_v1alpha1_BasicAuthOptions_To_v1beta1_BasicAuthOptions(in *BasicAuthOptions, out *v1beta1.BasicAuthOptions, s conversion.Scope) error {
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.User, &out.User, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.Password, &out.Password, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BasicAuthOptions_To_v1beta1_BasicAuthOptions is an autogenerated conversion function.
func Convert_v1alpha1_BasicAuthOptions_To_v1beta1_BasicAuthOptions(in *BasicAuthOptions, out *v1beta1.BasicAuthOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_BasicAuthOptions_To_v1beta1_BasicAuthOptions(in, out, s)
}

func autoConvert_v1beta1_BasicAuthOptions_To_v1alpha1_BasicAuthOptions(in *v1beta1.BasicAuthOptions, out *BasicAuthOptions, s conversion.Scope) error {
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.User, &out.User, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.Password, &out.Password, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_BasicAuthOptions_To_v1alpha1_BasicAuthOptions is an autogenerated conversion function.
func Convert_v1beta1_BasicAuthOptions_To_v1alpha1_BasicAuthOptions(in *v1beta1.BasicAuthOptions, out *BasicAuthOptions, s conversion.Scope) error {
	return autoConvert_v1beta1_BasicAuthOptions_To_v1alpha1_BasicAuthOptions(in, out, s)
}

func autoConvert_v1alpha1_EnvoyMetrics_To_v1beta1_EnvoyMetrics(in *EnvoyMetrics, out *v1beta1.EnvoyMetrics, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_EnvoyMetrics_To_v1beta1_EnvoyMetrics is an autogenerated conversion function.
func Convert_v1alpha1_EnvoyMetrics_To_v1beta1_EnvoyMetrics(in *EnvoyMetrics, out *v1beta1.EnvoyMetrics, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnvoyMetrics_To_v1beta1_EnvoyMetrics(in, out, s)
}

func autoConvert_v1beta1_EnvoyMetrics_To_v1alpha1_EnvoyMetrics(in *v1beta1.EnvoyMetrics, out *EnvoyMetrics, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta1_EnvoyMetrics_To_v1alpha1_EnvoyMetrics is an autogenerated conversion function.
func Convert_v1beta1_EnvoyMetrics_To_v1alpha1_EnvoyMetrics(in *v1beta1.EnvoyMetrics, out *EnvoyMetrics, s conversion.Scope) error {
	return autoConvert_v1beta1_EnvoyMetrics_To_v1alpha1_EnvoyMetrics(in, out, s)
}

func autoConvert_v1alpha1_FilterSpec_To_v1beta1_FilterSpec(in *FilterSpec, out *v1beta1.FilterSpec, s conversion.Scope) error {
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_FilterSpec_To_v1beta1_FilterSpec is an autogenerated conversion function.
func Convert_v1alpha1_FilterSpec_To_v1beta1_FilterSpec(in *FilterSpec, out *v1beta1.FilterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FilterSpec_To_v1beta1_FilterSpec(in, out, s)
}

func autoConvert_v1beta1_FilterSpec_To_v1alpha1_FilterSpec(in *v1beta1.FilterSpec, out *FilterSpec, s conversion.Scope) error {
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_FilterSpec_To_v1alpha1_FilterSpec is an autogenerated conversion function.
func Convert_v1beta1_FilterSpec_To_v1alpha1_FilterSpec(in *v1beta1.FilterSpec, out *FilterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_FilterSpec_To_v1alpha1_FilterSpec(in, out, s)
}

func autoConvert_v1alpha1_FluentBitFile_To_v1beta1_FluentBitFile(in *FluentBitFile, out *v1beta1.FluentBitFile, s conversion.Scope) error {
	out.Name = in.Name
	out.Content = in.Content
	return nil
}

// Convert_v1alpha1_FluentBitFile_To_v1beta1_FluentBitFile is an autogenerated conversion function.
func Convert_v1alpha1_FluentBitFile_To_v1beta1_FluentBitFile(in *FluentBitFile, out *v1beta1.FluentBitFile, s conversion.Scope) error {
	return autoConvert_v1alpha1_FluentBitFile_To_v1beta1_FluentBitFile(in, out, s)
}

func autoConvert_v1beta1_FluentBitFile_To_v1alpha1_FluentBitFile(in *v1beta1.FluentBitFile, out *FluentBitFile, s conversion.Scope) error {
	out.Name = in.Name
	out.Content = in.Content
	return nil
}

// Convert_v1beta1_FluentBitFile_To_v1alpha1_FluentBitFile is an autogenerated conversion function.
func Convert_v1beta1_FluentBitFile_To_v1alpha1_FluentBitFile(in *v1beta1.FluentBitFile, out *FluentBitFile, s conversion.Scope) error {
	return autoConvert_v1beta1_FluentBitFile_To_v1alpha1_FluentBitFile(in, out, s)
}

func autoConvert_v1alpha1_FluentBitFilter_To_v1beta1_FluentBitFilter(in *FluentBitFilter, out *v1beta1.FluentBitFilter, s conversion.Scope) error {
	out.Custom = in.Custom
	return nil
}

// Convert_v1alpha1_FluentBitFilter_To_v1beta1_FluentBitFilter is an autogenerated conversion function.
func Convert_v1alpha1_FluentBitFilter_To_v1beta1_FluentBitFilter(in *FluentBitFilter, out *v1beta1.FluentBitFilter, s conversion.Scope) error {
	return autoConvert_v1alpha1_FluentBitFilter_To_v1beta1_FluentBitFilter(in, out, s)
}

func autoConvert_v1beta1_FluentBitFilter_To_v1alpha1_FluentBitFilter(in *v1beta1.FluentBitFilter, out *FluentBitFilter, s conversion.Scope) error {
	out.Custom = in.Custom
	return nil
}

// Convert_v1beta1_FluentBitFilter_To_v1alpha1_FluentBitFilter is an autogenerated conversion function.
func Convert_v1beta1_FluentBitFilter_To_v1alpha1_FluentBitFilter(in *v1beta1.FluentBitFilter, out *FluentBitFilter, s conversion.Scope) error {
	return autoConvert_v1beta1_FluentBitFilter_To_v1alpha1_FluentBitFilter(in, out, s)
}

func autoConvert_v1alpha1_FluentBitHTTPOutput_To_v1beta1_FluentBitHTTPOutput(in *FluentBitHTTPOutput, out *v1beta1.FluentBitHTTPOutput, s conversion.Scope) error {
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.Host, &out.Host, s); err != nil {
		return err
	}
	out.User = (*v1beta1.ValueType)(unsafe.Pointer(in.User))
	out.Password = (*v1beta1.ValueType)(unsafe.Pointer(in.Password))
	out.URI = in.URI
	out.Port = in.Port
	out.Compress = in.Compress
	out.Format = in.Format
	if err := Convert_v1alpha1_FluentBitHTTPOutputTLS_To_v1beta1_OutputTLS(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	out.Dedot = in.Dedot
	return nil
}

// Convert_v1alpha1_FluentBitHTTPOutput_To_v1beta1_FluentBitHTTPOutput is an autogenerated conversion function.
func Convert_v1alpha1_FluentBitHTTPOutput_To_v1beta1_FluentBitHTTPOutput(in *FluentBitHTTPOutput, out *v1beta1.FluentBitHTTPOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_FluentBitHTTPOutput_To_v1beta1_FluentBitHTTPOutput(in, out, s)
}

func autoConvert_v1beta1_FluentBitHTTPOutput_To_v1alpha1_FluentBitHTTPOutput(in *v1beta1.FluentBitHTTPOutput, out *FluentBitHTTPOutput, s conversion.Scope) error {
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.Host, &out.Host, s); err != nil {
		return err
	}
	out.User = (*ValueType)(unsafe.Pointer(in.User))
	out.Password = (*ValueType)(unsafe.Pointer(in.Password))
	out.URI = in.URI
	out.Port = in.Port
	out.Compress = in.Compress
	out.Format = in.Format
	if err := Convert_v1beta1_OutputTLS_To_v1alpha1_FluentBitHTTPOutputTLS(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	out.Dedot = in.Dedot
	return nil
}

// Convert_v1beta1_FluentBitHTTPOutput_To_v1alpha1_FluentBitHTTPOutput is an autogenerated conversion function.
func Convert_v1beta1_FluentBitHTTPOutput_To_v1alpha1_FluentBitHTTPOutput(in *v1beta1.FluentBitHTTPOutput, out *FluentBitHTTPOutput, s conversion.Scope) error {
	return autoConvert_v1beta1_FluentBitHTTPOutput_To_v1alpha1_FluentBitHTTPOutput(in, out, s)
}

func autoConvert_v1alpha1_FluentBitVariable_To_v1beta1_FluentBitVariable(in *FluentBitVariable, out *v1beta1.FluentBitVariable, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_ValueFromSource_To_v1beta1_ValueFromSource(&in.ValueFrom, &out.ValueFrom, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_FluentBitVariable_To_v1beta1_FluentBitVariable is an autogenerated conversion function.
func Convert_v1alpha1_FluentBitVariable_To_v1beta1_FluentBitVariable(in *FluentBitVariable, out *v1beta1.FluentBitVariable, s conversion.Scope) error {
	return autoConvert_v1alpha1_FluentBitVariable_To_v1beta1_FluentBitVariable(in, out, s)
}

func autoConvert_v1beta1_FluentBitVariable_To_v1alpha1_FluentBitVariable(in *v1beta1.FluentBitVariable, out *FluentBitVariable, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1beta1_ValueFromSource_To_v1alpha1_ValueFromSource(&in.ValueFrom, &out.ValueFrom, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_FluentBitVariable_To_v1alpha1_FluentBitVariable is an autogenerated conversion function.
func Convert_v1beta1_FluentBitVariable_To_v1alpha1_FluentBitVariable(in *v1beta1.FluentBitVariable, out *FluentBitVariable, s conversion.Scope) error {
	return autoConvert_v1beta1_FluentBitVariable_To_v1alpha1_FluentBitVariable(in, out, s)
}

func autoConvert_v1alpha1_Header_To_v1beta1_Header(in *Header, out *v1beta1.Header, s conversion.Scope) error {
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.ValueType, &out.ValueType, s); err != nil {
		return err
	}
	out.Name = in.Name
	out.Prefix = in.Prefix
	return nil
}

// Convert_v1alpha1_Header_To_v1beta1_Header is an autogenerated conversion function.
func Convert_v1alpha1_Header_To_v1beta1_Header(in *Header, out *v1beta1.Header, s conversion.Scope) error {
	return autoConvert_v1alpha1_Header_To_v1beta1_Header(in, out, s)
}

func autoConvert_v1beta1_Header_To_v1alpha1_Header(in *v1beta1.Header, out *Header, s conversion.Scope) error {
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.ValueType, &out.ValueType, s); err != nil {
		return err
	}
	out.Name = in.Name
	out.Prefix = in.Prefix
	return nil
}

// Convert_v1beta1_Header_To_v1alpha1_Header is an autogenerated conversion function.
func Convert_v1beta1_Header_To_v1alpha1_Header(in *v1beta1.Header, out *Header, s conversion.Scope) error {
	return autoConvert_v1beta1_Header_To_v1alpha1_Header(in, out, s)
}

func autoConvert_v1alpha1_LogPipeline_To_v1beta1_LogPipeline(in *LogPipeline, out *v1beta1.LogPipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LogPipelineSpec_To_v1beta1_LogPipelineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LogPipelineStatus_To_v1beta1_LogPipelineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LogPipeline_To_v1beta1_LogPipeline is an autogenerated conversion function.
func Convert_v1alpha1_LogPipeline_To_v1beta1_LogPipeline(in *LogPipeline, out *v1beta1.LogPipeline, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogPipeline_To_v1beta1_LogPipeline(in, out, s)
}

func autoConvert_v1beta1_LogPipeline_To_v1alpha1_LogPipeline(in *v1beta1.LogPipeline, out *LogPipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_LogPipelineSpec_To_v1alpha1_LogPipelineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_LogPipelineStatus_To_v1alpha1_LogPipelineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_LogPipeline_To_v1alpha1_LogPipeline is an autogenerated conversion function.
func Convert_v1beta1_LogPipeline_To_v1alpha1_LogPipeline(in *v1beta1.LogPipeline, out *LogPipeline, s conversion.Scope) error {
	return autoConvert_v1beta1_LogPipeline_To_v1alpha1_LogPipeline(in, out, s)
}

func autoConvert_v1alpha1_LogPipelineContainerSelector_To_v1beta1_LogPipelineContainerSelector(in *LogPipelineContainerSelector, out *v1beta1.LogPipelineContainerSelector, s conversion.Scope) error {
	out.Include = *(*[]string)(unsafe.Pointer(&in.Include))
	out.Exclude = *(*[]string)(unsafe.Pointer(&in.Exclude))
	return nil
}

// Convert_v1alpha1_LogPipelineContainerSelector_To_v1beta1_LogPipelineContainerSelector is an autogenerated conversion function.
func Convert_v1alpha1_LogPipelineContainerSelector_To_v1beta1_LogPipelineContainerSelector(in *LogPipelineContainerSelector, out *v1beta1.LogPipelineContainerSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogPipelineContainerSelector_To_v1beta1_LogPipelineContainerSelector(in, out, s)
}

func autoConvert_v1beta1_LogPipelineContainerSelector_To_v1alpha1_LogPipelineContainerSelector(in *v1beta1.LogPipelineContainerSelector, out *LogPipelineContainerSelector, s conversion.Scope) error {
	out.Include = *(*[]string)(unsafe.Pointer(&in.Include))
	out.Exclude = *(*[]string)(unsafe.Pointer(&in.Exclude))
	return nil
}

// Convert_v1beta1_LogPipelineContainerSelector_To_v1alpha1_LogPipelineContainerSelector is an autogenerated conversion function.
func Convert_v1beta1_LogPipelineContainerSelector_To_v1alpha1_LogPipelineContainerSelector(in *v1beta1.LogPipelineContainerSelector, out *LogPipelineContainerSelector, s conversion.Scope) error {
	return autoConvert_v1beta1_LogPipelineContainerSelector_To_v1alpha1_LogPipelineContainerSelector(in, out, s)
}

func autoConvert_v1alpha1_LogPipelineInput_To_v1beta1_LogPipelineInput(in *LogPipelineInput, out *v1beta1.LogPipelineInput, s conversion.Scope) error {
	// WARNING: in.Application requires manual conversion: does not exist in peer-type
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(v1beta1.OTLPInput)
		if err := Convert_v1alpha1_OTLPInput_To_v1beta1_OTLPInput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OTLP = nil
	}
	return nil
}

func autoConvert_v1beta1_LogPipelineInput_To_v1alpha1_LogPipelineInput(in *v1beta1.LogPipelineInput, out *LogPipelineInput, s conversion.Scope) error {
	// WARNING: in.Runtime requires manual conversion: does not exist in peer-type
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLPInput)
		if err := Convert_v1beta1_OTLPInput_To_v1alpha1_OTLPInput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OTLP = nil
	}
	return nil
}

func autoConvert_v1alpha1_LogPipelineList_To_v1beta1_LogPipelineList(in *LogPipelineList, out *v1beta1.LogPipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.LogPipeline, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_LogPipeline_To_v1beta1_LogPipeline(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_LogPipelineList_To_v1beta1_LogPipelineList is an autogenerated conversion function.
func Convert_v1alpha1_LogPipelineList_To_v1beta1_LogPipelineList(in *LogPipelineList, out *v1beta1.LogPipelineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogPipelineList_To_v1beta1_LogPipelineList(in, out, s)
}

func autoConvert_v1beta1_LogPipelineList_To_v1alpha1_LogPipelineList(in *v1beta1.LogPipelineList, out *LogPipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogPipeline, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_LogPipeline_To_v1alpha1_LogPipeline(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_LogPipelineList_To_v1alpha1_LogPipelineList is an autogenerated conversion function.
func Convert_v1beta1_LogPipelineList_To_v1alpha1_LogPipelineList(in *v1beta1.LogPipelineList, out *LogPipelineList, s conversion.Scope) error {
	return autoConvert_v1beta1_LogPipelineList_To_v1alpha1_LogPipelineList(in, out, s)
}

func autoConvert_v1alpha1_LogPipelineOutput_To_v1beta1_LogPipelineOutput(in *LogPipelineOutput, out *v1beta1.LogPipelineOutput, s conversion.Scope) error {
	out.FluentBitCustom = in.FluentBitCustom
	if in.FluentBitHTTP != nil {
		in, out := &in.FluentBitHTTP, &out.FluentBitHTTP
		*out = new(v1beta1.FluentBitHTTPOutput)
		if err := Convert_v1alpha1_FluentBitHTTPOutput_To_v1beta1_FluentBitHTTPOutput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.FluentBitHTTP = nil
	}
	out.OTLP = (*v1beta1.OTLPOutput)(unsafe.Pointer(in.OTLP))
	return nil
}

// Convert_v1alpha1_LogPipelineOutput_To_v1beta1_LogPipelineOutput is an autogenerated conversion function.
func Convert_v1alpha1_LogPipelineOutput_To_v1beta1_LogPipelineOutput(in *LogPipelineOutput, out *v1beta1.LogPipelineOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogPipelineOutput_To_v1beta1_LogPipelineOutput(in, out, s)
}

func autoConvert_v1beta1_LogPipelineOutput_To_v1alpha1_LogPipelineOutput(in *v1beta1.LogPipelineOutput, out *LogPipelineOutput, s conversion.Scope) error {
	out.FluentBitCustom = in.FluentBitCustom
	if in.FluentBitHTTP != nil {
		in, out := &in.FluentBitHTTP, &out.FluentBitHTTP
		*out = new(FluentBitHTTPOutput)
		if err := Convert_v1beta1_FluentBitHTTPOutput_To_v1alpha1_FluentBitHTTPOutput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.FluentBitHTTP = nil
	}
	out.OTLP = (*OTLPOutput)(unsafe.Pointer(in.OTLP))
	return nil
}

// Convert_v1beta1_LogPipelineOutput_To_v1alpha1_LogPipelineOutput is an autogenerated conversion function.
func Convert_v1beta1_LogPipelineOutput_To_v1alpha1_LogPipelineOutput(in *v1beta1.LogPipelineOutput, out *LogPipelineOutput, s conversion.Scope) error {
	return autoConvert_v1beta1_LogPipelineOutput_To_v1alpha1_LogPipelineOutput(in, out, s)
}

func autoConvert_v1alpha1_LogPipelineSpec_To_v1beta1_LogPipelineSpec(in *LogPipelineSpec, out *v1beta1.LogPipelineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LogPipelineInput_To_v1beta1_LogPipelineInput(&in.Input, &out.Input, s); err != nil {
		return err
	}
	out.FluentBitFilters = *(*[]v1beta1.FluentBitFilter)(unsafe.Pointer(&in.FluentBitFilters))
	if err := Convert_v1alpha1_LogPipelineOutput_To_v1beta1_LogPipelineOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	out.FluentBitFiles = *(*[]v1beta1.FluentBitFile)(unsafe.Pointer(&in.FluentBitFiles))
	out.FluentBitVariables = *(*[]v1beta1.FluentBitVariable)(unsafe.Pointer(&in.FluentBitVariables))
	out.Transforms = *(*[]v1beta1.TransformSpec)(unsafe.Pointer(&in.Transforms))
	out.Filters = *(*[]v1beta1.FilterSpec)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1alpha1_LogPipelineSpec_To_v1beta1_LogPipelineSpec is an autogenerated conversion function.
func Convert_v1alpha1_LogPipelineSpec_To_v1beta1_LogPipelineSpec(in *LogPipelineSpec, out *v1beta1.LogPipelineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogPipelineSpec_To_v1beta1_LogPipelineSpec(in, out, s)
}

func autoConvert_v1beta1_LogPipelineSpec_To_v1alpha1_LogPipelineSpec(in *v1beta1.LogPipelineSpec, out *LogPipelineSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_LogPipelineInput_To_v1alpha1_LogPipelineInput(&in.Input, &out.Input, s); err != nil {
		return err
	}
	out.FluentBitFilters = *(*[]FluentBitFilter)(unsafe.Pointer(&in.FluentBitFilters))
	if err := Convert_v1beta1_LogPipelineOutput_To_v1alpha1_LogPipelineOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	out.FluentBitFiles = *(*[]FluentBitFile)(unsafe.Pointer(&in.FluentBitFiles))
	out.FluentBitVariables = *(*[]FluentBitVariable)(unsafe.Pointer(&in.FluentBitVariables))
	out.Transforms = *(*[]TransformSpec)(unsafe.Pointer(&in.Transforms))
	out.Filters = *(*[]FilterSpec)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1beta1_LogPipelineSpec_To_v1alpha1_LogPipelineSpec is an autogenerated conversion function.
func Convert_v1beta1_LogPipelineSpec_To_v1alpha1_LogPipelineSpec(in *v1beta1.LogPipelineSpec, out *LogPipelineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_LogPipelineSpec_To_v1alpha1_LogPipelineSpec(in, out, s)
}

func autoConvert_v1alpha1_LogPipelineStatus_To_v1beta1_LogPipelineStatus(in *LogPipelineStatus, out *v1beta1.LogPipelineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.UnsupportedMode = (*bool)(unsafe.Pointer(in.UnsupportedMode))
	return nil
}

// Convert_v1alpha1_LogPipelineStatus_To_v1beta1_LogPipelineStatus is an autogenerated conversion function.
func Convert_v1alpha1_LogPipelineStatus_To_v1beta1_LogPipelineStatus(in *LogPipelineStatus, out *v1beta1.LogPipelineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LogPipelineStatus_To_v1beta1_LogPipelineStatus(in, out, s)
}

func autoConvert_v1beta1_LogPipelineStatus_To_v1alpha1_LogPipelineStatus(in *v1beta1.LogPipelineStatus, out *LogPipelineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.UnsupportedMode = (*bool)(unsafe.Pointer(in.UnsupportedMode))
	return nil
}

// Convert_v1beta1_LogPipelineStatus_To_v1alpha1_LogPipelineStatus is an autogenerated conversion function.
func Convert_v1beta1_LogPipelineStatus_To_v1alpha1_LogPipelineStatus(in *v1beta1.LogPipelineStatus, out *LogPipelineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_LogPipelineStatus_To_v1alpha1_LogPipelineStatus(in, out, s)
}

func autoConvert_v1alpha1_MetricPipeline_To_v1beta1_MetricPipeline(in *MetricPipeline, out *v1beta1.MetricPipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MetricPipelineSpec_To_v1beta1_MetricPipelineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MetricPipelineStatus_To_v1beta1_MetricPipelineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MetricPipeline_To_v1beta1_MetricPipeline is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipeline_To_v1beta1_MetricPipeline(in *MetricPipeline, out *v1beta1.MetricPipeline, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipeline_To_v1beta1_MetricPipeline(in, out, s)
}

func autoConvert_v1beta1_MetricPipeline_To_v1alpha1_MetricPipeline(in *v1beta1.MetricPipeline, out *MetricPipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_MetricPipelineSpec_To_v1alpha1_MetricPipelineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MetricPipelineStatus_To_v1alpha1_MetricPipelineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MetricPipeline_To_v1alpha1_MetricPipeline is an autogenerated conversion function.
func Convert_v1beta1_MetricPipeline_To_v1alpha1_MetricPipeline(in *v1beta1.MetricPipeline, out *MetricPipeline, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipeline_To_v1alpha1_MetricPipeline(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineInput_To_v1beta1_MetricPipelineInput(in *MetricPipelineInput, out *v1beta1.MetricPipelineInput, s conversion.Scope) error {
	out.Prometheus = (*v1beta1.MetricPipelinePrometheusInput)(unsafe.Pointer(in.Prometheus))
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(v1beta1.MetricPipelineRuntimeInput)
		if err := Convert_v1alpha1_MetricPipelineRuntimeInput_To_v1beta1_MetricPipelineRuntimeInput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Runtime = nil
	}
	out.Istio = (*v1beta1.MetricPipelineIstioInput)(unsafe.Pointer(in.Istio))
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(v1beta1.OTLPInput)
		if err := Convert_v1alpha1_OTLPInput_To_v1beta1_OTLPInput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OTLP = nil
	}
	return nil
}

// Convert_v1alpha1_MetricPipelineInput_To_v1beta1_MetricPipelineInput is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineInput_To_v1beta1_MetricPipelineInput(in *MetricPipelineInput, out *v1beta1.MetricPipelineInput, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineInput_To_v1beta1_MetricPipelineInput(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineInput_To_v1alpha1_MetricPipelineInput(in *v1beta1.MetricPipelineInput, out *MetricPipelineInput, s conversion.Scope) error {
	out.Prometheus = (*MetricPipelinePrometheusInput)(unsafe.Pointer(in.Prometheus))
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(MetricPipelineRuntimeInput)
		if err := Convert_v1beta1_MetricPipelineRuntimeInput_To_v1alpha1_MetricPipelineRuntimeInput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Runtime = nil
	}
	out.Istio = (*MetricPipelineIstioInput)(unsafe.Pointer(in.Istio))
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLPInput)
		if err := Convert_v1beta1_OTLPInput_To_v1alpha1_OTLPInput(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OTLP = nil
	}
	return nil
}

// Convert_v1beta1_MetricPipelineInput_To_v1alpha1_MetricPipelineInput is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineInput_To_v1alpha1_MetricPipelineInput(in *v1beta1.MetricPipelineInput, out *MetricPipelineInput, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineInput_To_v1alpha1_MetricPipelineInput(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineIstioInput_To_v1beta1_MetricPipelineIstioInput(in *MetricPipelineIstioInput, out *v1beta1.MetricPipelineIstioInput, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Namespaces = (*v1beta1.NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	out.DiagnosticMetrics = (*v1beta1.MetricPipelineIstioInputDiagnosticMetrics)(unsafe.Pointer(in.DiagnosticMetrics))
	out.EnvoyMetrics = (*v1beta1.EnvoyMetrics)(unsafe.Pointer(in.EnvoyMetrics))
	return nil
}

// Convert_v1alpha1_MetricPipelineIstioInput_To_v1beta1_MetricPipelineIstioInput is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineIstioInput_To_v1beta1_MetricPipelineIstioInput(in *MetricPipelineIstioInput, out *v1beta1.MetricPipelineIstioInput, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineIstioInput_To_v1beta1_MetricPipelineIstioInput(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineIstioInput_To_v1alpha1_MetricPipelineIstioInput(in *v1beta1.MetricPipelineIstioInput, out *MetricPipelineIstioInput, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Namespaces = (*NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	out.DiagnosticMetrics = (*MetricPipelineIstioInputDiagnosticMetrics)(unsafe.Pointer(in.DiagnosticMetrics))
	out.EnvoyMetrics = (*EnvoyMetrics)(unsafe.Pointer(in.EnvoyMetrics))
	return nil
}

// Convert_v1beta1_MetricPipelineIstioInput_To_v1alpha1_MetricPipelineIstioInput is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineIstioInput_To_v1alpha1_MetricPipelineIstioInput(in *v1beta1.MetricPipelineIstioInput, out *MetricPipelineIstioInput, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineIstioInput_To_v1alpha1_MetricPipelineIstioInput(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics_To_v1beta1_MetricPipelineIstioInputDiagnosticMetrics(in *MetricPipelineIstioInputDiagnosticMetrics, out *v1beta1.MetricPipelineIstioInputDiagnosticMetrics, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics_To_v1beta1_MetricPipelineIstioInputDiagnosticMetrics is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics_To_v1beta1_MetricPipelineIstioInputDiagnosticMetrics(in *MetricPipelineIstioInputDiagnosticMetrics, out *v1beta1.MetricPipelineIstioInputDiagnosticMetrics, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics_To_v1beta1_MetricPipelineIstioInputDiagnosticMetrics(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineIstioInputDiagnosticMetrics_To_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics(in *v1beta1.MetricPipelineIstioInputDiagnosticMetrics, out *MetricPipelineIstioInputDiagnosticMetrics, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta1_MetricPipelineIstioInputDiagnosticMetrics_To_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineIstioInputDiagnosticMetrics_To_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics(in *v1beta1.MetricPipelineIstioInputDiagnosticMetrics, out *MetricPipelineIstioInputDiagnosticMetrics, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineIstioInputDiagnosticMetrics_To_v1alpha1_MetricPipelineIstioInputDiagnosticMetrics(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineList_To_v1beta1_MetricPipelineList(in *MetricPipelineList, out *v1beta1.MetricPipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.MetricPipeline, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_MetricPipeline_To_v1beta1_MetricPipeline(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_MetricPipelineList_To_v1beta1_MetricPipelineList is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineList_To_v1beta1_MetricPipelineList(in *MetricPipelineList, out *v1beta1.MetricPipelineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineList_To_v1beta1_MetricPipelineList(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineList_To_v1alpha1_MetricPipelineList(in *v1beta1.MetricPipelineList, out *MetricPipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetricPipeline, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_MetricPipeline_To_v1alpha1_MetricPipeline(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_MetricPipelineList_To_v1alpha1_MetricPipelineList is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineList_To_v1alpha1_MetricPipelineList(in *v1beta1.MetricPipelineList, out *MetricPipelineList, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineList_To_v1alpha1_MetricPipelineList(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineOutput_To_v1beta1_MetricPipelineOutput(in *MetricPipelineOutput, out *v1beta1.MetricPipelineOutput, s conversion.Scope) error {
	out.OTLP = (*v1beta1.OTLPOutput)(unsafe.Pointer(in.OTLP))
	return nil
}

// Convert_v1alpha1_MetricPipelineOutput_To_v1beta1_MetricPipelineOutput is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineOutput_To_v1beta1_MetricPipelineOutput(in *MetricPipelineOutput, out *v1beta1.MetricPipelineOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineOutput_To_v1beta1_MetricPipelineOutput(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineOutput_To_v1alpha1_MetricPipelineOutput(in *v1beta1.MetricPipelineOutput, out *MetricPipelineOutput, s conversion.Scope) error {
	out.OTLP = (*OTLPOutput)(unsafe.Pointer(in.OTLP))
	return nil
}

// Convert_v1beta1_MetricPipelineOutput_To_v1alpha1_MetricPipelineOutput is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineOutput_To_v1alpha1_MetricPipelineOutput(in *v1beta1.MetricPipelineOutput, out *MetricPipelineOutput, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineOutput_To_v1alpha1_MetricPipelineOutput(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelinePrometheusInput_To_v1beta1_MetricPipelinePrometheusInput(in *MetricPipelinePrometheusInput, out *v1beta1.MetricPipelinePrometheusInput, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Namespaces = (*v1beta1.NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	out.DiagnosticMetrics = (*v1beta1.MetricPipelineIstioInputDiagnosticMetrics)(unsafe.Pointer(in.DiagnosticMetrics))
	return nil
}

// Convert_v1alpha1_MetricPipelinePrometheusInput_To_v1beta1_MetricPipelinePrometheusInput is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelinePrometheusInput_To_v1beta1_MetricPipelinePrometheusInput(in *MetricPipelinePrometheusInput, out *v1beta1.MetricPipelinePrometheusInput, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelinePrometheusInput_To_v1beta1_MetricPipelinePrometheusInput(in, out, s)
}

func autoConvert_v1beta1_MetricPipelinePrometheusInput_To_v1alpha1_MetricPipelinePrometheusInput(in *v1beta1.MetricPipelinePrometheusInput, out *MetricPipelinePrometheusInput, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Namespaces = (*NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	out.DiagnosticMetrics = (*MetricPipelineIstioInputDiagnosticMetrics)(unsafe.Pointer(in.DiagnosticMetrics))
	return nil
}

// Convert_v1beta1_MetricPipelinePrometheusInput_To_v1alpha1_MetricPipelinePrometheusInput is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelinePrometheusInput_To_v1alpha1_MetricPipelinePrometheusInput(in *v1beta1.MetricPipelinePrometheusInput, out *MetricPipelinePrometheusInput, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelinePrometheusInput_To_v1alpha1_MetricPipelinePrometheusInput(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineRuntimeInput_To_v1beta1_MetricPipelineRuntimeInput(in *MetricPipelineRuntimeInput, out *v1beta1.MetricPipelineRuntimeInput, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Namespaces = (*v1beta1.NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	out.Resources = (*v1beta1.MetricPipelineRuntimeInputResources)(unsafe.Pointer(in.Resources))
	return nil
}

func autoConvert_v1beta1_MetricPipelineRuntimeInput_To_v1alpha1_MetricPipelineRuntimeInput(in *v1beta1.MetricPipelineRuntimeInput, out *MetricPipelineRuntimeInput, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	out.Namespaces = (*NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	out.Resources = (*MetricPipelineRuntimeInputResources)(unsafe.Pointer(in.Resources))
	return nil
}

// Convert_v1beta1_MetricPipelineRuntimeInput_To_v1alpha1_MetricPipelineRuntimeInput is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineRuntimeInput_To_v1alpha1_MetricPipelineRuntimeInput(in *v1beta1.MetricPipelineRuntimeInput, out *MetricPipelineRuntimeInput, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineRuntimeInput_To_v1alpha1_MetricPipelineRuntimeInput(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineRuntimeInputResource_To_v1beta1_MetricPipelineRuntimeInputResource(in *MetricPipelineRuntimeInputResource, out *v1beta1.MetricPipelineRuntimeInputResource, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_MetricPipelineRuntimeInputResource_To_v1beta1_MetricPipelineRuntimeInputResource is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineRuntimeInputResource_To_v1beta1_MetricPipelineRuntimeInputResource(in *MetricPipelineRuntimeInputResource, out *v1beta1.MetricPipelineRuntimeInputResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineRuntimeInputResource_To_v1beta1_MetricPipelineRuntimeInputResource(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineRuntimeInputResource_To_v1alpha1_MetricPipelineRuntimeInputResource(in *v1beta1.MetricPipelineRuntimeInputResource, out *MetricPipelineRuntimeInputResource, s conversion.Scope) error {
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta1_MetricPipelineRuntimeInputResource_To_v1alpha1_MetricPipelineRuntimeInputResource is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineRuntimeInputResource_To_v1alpha1_MetricPipelineRuntimeInputResource(in *v1beta1.MetricPipelineRuntimeInputResource, out *MetricPipelineRuntimeInputResource, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineRuntimeInputResource_To_v1alpha1_MetricPipelineRuntimeInputResource(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineRuntimeInputResources_To_v1beta1_MetricPipelineRuntimeInputResources(in *MetricPipelineRuntimeInputResources, out *v1beta1.MetricPipelineRuntimeInputResources, s conversion.Scope) error {
	out.Pod = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Pod))
	out.Container = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Container))
	out.Node = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Node))
	out.Volume = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Volume))
	out.DaemonSet = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.DaemonSet))
	out.Deployment = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Deployment))
	out.StatefulSet = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.StatefulSet))
	out.Job = (*v1beta1.MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Job))
	return nil
}

// Convert_v1alpha1_MetricPipelineRuntimeInputResources_To_v1beta1_MetricPipelineRuntimeInputResources is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineRuntimeInputResources_To_v1beta1_MetricPipelineRuntimeInputResources(in *MetricPipelineRuntimeInputResources, out *v1beta1.MetricPipelineRuntimeInputResources, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineRuntimeInputResources_To_v1beta1_MetricPipelineRuntimeInputResources(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineRuntimeInputResources_To_v1alpha1_MetricPipelineRuntimeInputResources(in *v1beta1.MetricPipelineRuntimeInputResources, out *MetricPipelineRuntimeInputResources, s conversion.Scope) error {
	out.Pod = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Pod))
	out.Container = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Container))
	out.Node = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Node))
	out.Volume = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Volume))
	out.DaemonSet = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.DaemonSet))
	out.Deployment = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Deployment))
	out.StatefulSet = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.StatefulSet))
	out.Job = (*MetricPipelineRuntimeInputResource)(unsafe.Pointer(in.Job))
	return nil
}

// Convert_v1beta1_MetricPipelineRuntimeInputResources_To_v1alpha1_MetricPipelineRuntimeInputResources is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineRuntimeInputResources_To_v1alpha1_MetricPipelineRuntimeInputResources(in *v1beta1.MetricPipelineRuntimeInputResources, out *MetricPipelineRuntimeInputResources, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineRuntimeInputResources_To_v1alpha1_MetricPipelineRuntimeInputResources(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineSpec_To_v1beta1_MetricPipelineSpec(in *MetricPipelineSpec, out *v1beta1.MetricPipelineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_MetricPipelineInput_To_v1beta1_MetricPipelineInput(&in.Input, &out.Input, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MetricPipelineOutput_To_v1beta1_MetricPipelineOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	out.Transforms = *(*[]v1beta1.TransformSpec)(unsafe.Pointer(&in.Transforms))
	out.Filters = *(*[]v1beta1.FilterSpec)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1alpha1_MetricPipelineSpec_To_v1beta1_MetricPipelineSpec is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineSpec_To_v1beta1_MetricPipelineSpec(in *MetricPipelineSpec, out *v1beta1.MetricPipelineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineSpec_To_v1beta1_MetricPipelineSpec(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineSpec_To_v1alpha1_MetricPipelineSpec(in *v1beta1.MetricPipelineSpec, out *MetricPipelineSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_MetricPipelineInput_To_v1alpha1_MetricPipelineInput(&in.Input, &out.Input, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_MetricPipelineOutput_To_v1alpha1_MetricPipelineOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	out.Transforms = *(*[]TransformSpec)(unsafe.Pointer(&in.Transforms))
	out.Filters = *(*[]FilterSpec)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1beta1_MetricPipelineSpec_To_v1alpha1_MetricPipelineSpec is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineSpec_To_v1alpha1_MetricPipelineSpec(in *v1beta1.MetricPipelineSpec, out *MetricPipelineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineSpec_To_v1alpha1_MetricPipelineSpec(in, out, s)
}

func autoConvert_v1alpha1_MetricPipelineStatus_To_v1beta1_MetricPipelineStatus(in *MetricPipelineStatus, out *v1beta1.MetricPipelineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_MetricPipelineStatus_To_v1beta1_MetricPipelineStatus is an autogenerated conversion function.
func Convert_v1alpha1_MetricPipelineStatus_To_v1beta1_MetricPipelineStatus(in *MetricPipelineStatus, out *v1beta1.MetricPipelineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetricPipelineStatus_To_v1beta1_MetricPipelineStatus(in, out, s)
}

func autoConvert_v1beta1_MetricPipelineStatus_To_v1alpha1_MetricPipelineStatus(in *v1beta1.MetricPipelineStatus, out *MetricPipelineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_MetricPipelineStatus_To_v1alpha1_MetricPipelineStatus is an autogenerated conversion function.
func Convert_v1beta1_MetricPipelineStatus_To_v1alpha1_MetricPipelineStatus(in *v1beta1.MetricPipelineStatus, out *MetricPipelineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_MetricPipelineStatus_To_v1alpha1_MetricPipelineStatus(in, out, s)
}

func autoConvert_v1alpha1_NamespaceSelector_To_v1beta1_NamespaceSelector(in *NamespaceSelector, out *v1beta1.NamespaceSelector, s conversion.Scope) error {
	out.Include = *(*[]string)(unsafe.Pointer(&in.Include))
	out.Exclude = *(*[]string)(unsafe.Pointer(&in.Exclude))
	return nil
}

// Convert_v1alpha1_NamespaceSelector_To_v1beta1_NamespaceSelector is an autogenerated conversion function.
func Convert_v1alpha1_NamespaceSelector_To_v1beta1_NamespaceSelector(in *NamespaceSelector, out *v1beta1.NamespaceSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_NamespaceSelector_To_v1beta1_NamespaceSelector(in, out, s)
}

func autoConvert_v1beta1_NamespaceSelector_To_v1alpha1_NamespaceSelector(in *v1beta1.NamespaceSelector, out *NamespaceSelector, s conversion.Scope) error {
	out.Include = *(*[]string)(unsafe.Pointer(&in.Include))
	out.Exclude = *(*[]string)(unsafe.Pointer(&in.Exclude))
	return nil
}

// Convert_v1beta1_NamespaceSelector_To_v1alpha1_NamespaceSelector is an autogenerated conversion function.
func Convert_v1beta1_NamespaceSelector_To_v1alpha1_NamespaceSelector(in *v1beta1.NamespaceSelector, out *NamespaceSelector, s conversion.Scope) error {
	return autoConvert_v1beta1_NamespaceSelector_To_v1alpha1_NamespaceSelector(in, out, s)
}

func autoConvert_v1alpha1_OAuth2Options_To_v1beta1_OAuth2Options(in *OAuth2Options, out *v1beta1.OAuth2Options, s conversion.Scope) error {
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.TokenURL, &out.TokenURL, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.ClientID, &out.ClientID, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.ClientSecret, &out.ClientSecret, s); err != nil {
		return err
	}
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.Params = *(*map[string]string)(unsafe.Pointer(&in.Params))
	return nil
}

// Convert_v1alpha1_OAuth2Options_To_v1beta1_OAuth2Options is an autogenerated conversion function.
func Convert_v1alpha1_OAuth2Options_To_v1beta1_OAuth2Options(in *OAuth2Options, out *v1beta1.OAuth2Options, s conversion.Scope) error {
	return autoConvert_v1alpha1_OAuth2Options_To_v1beta1_OAuth2Options(in, out, s)
}

func autoConvert_v1beta1_OAuth2Options_To_v1alpha1_OAuth2Options(in *v1beta1.OAuth2Options, out *OAuth2Options, s conversion.Scope) error {
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.TokenURL, &out.TokenURL, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.ClientID, &out.ClientID, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.ClientSecret, &out.ClientSecret, s); err != nil {
		return err
	}
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.Params = *(*map[string]string)(unsafe.Pointer(&in.Params))
	return nil
}

// Convert_v1beta1_OAuth2Options_To_v1alpha1_OAuth2Options is an autogenerated conversion function.
func Convert_v1beta1_OAuth2Options_To_v1alpha1_OAuth2Options(in *v1beta1.OAuth2Options, out *OAuth2Options, s conversion.Scope) error {
	return autoConvert_v1beta1_OAuth2Options_To_v1alpha1_OAuth2Options(in, out, s)
}

func autoConvert_v1alpha1_OTLPInput_To_v1beta1_OTLPInput(in *OTLPInput, out *v1beta1.OTLPInput, s conversion.Scope) error {
	// WARNING: in.Disabled requires manual conversion: does not exist in peer-type
	out.Namespaces = (*v1beta1.NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	return nil
}

func autoConvert_v1beta1_OTLPInput_To_v1alpha1_OTLPInput(in *v1beta1.OTLPInput, out *OTLPInput, s conversion.Scope) error {
	// WARNING: in.Enabled requires manual conversion: does not exist in peer-type
	out.Namespaces = (*NamespaceSelector)(unsafe.Pointer(in.Namespaces))
	return nil
}

func autoConvert_v1alpha1_OTLPOutput_To_v1beta1_OTLPOutput(in *OTLPOutput, out *v1beta1.OTLPOutput, s conversion.Scope) error {
	out.Protocol = v1beta1.OTLPProtocol(in.Protocol)
	if err := Convert_v1alpha1_ValueType_To_v1beta1_ValueType(&in.Endpoint, &out.Endpoint, s); err != nil {
		return err
	}
	out.Path = in.Path
	out.Authentication = (*v1beta1.AuthenticationOptions)(unsafe.Pointer(in.Authentication))
	out.Headers = *(*[]v1beta1.Header)(unsafe.Pointer(&in.Headers))
	out.TLS = (*v1beta1.OutputTLS)(unsafe.Pointer(in.TLS))
	return nil
}

// Convert_v1alpha1_OTLPOutput_To_v1beta1_OTLPOutput is an autogenerated conversion function.
func Convert_v1alpha1_OTLPOutput_To_v1beta1_OTLPOutput(in *OTLPOutput, out *v1beta1.OTLPOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_OTLPOutput_To_v1beta1_OTLPOutput(in, out, s)
}

func autoConvert_v1beta1_OTLPOutput_To_v1alpha1_OTLPOutput(in *v1beta1.OTLPOutput, out *OTLPOutput, s conversion.Scope) error {
	out.Protocol = string(in.Protocol)
	if err := Convert_v1beta1_ValueType_To_v1alpha1_ValueType(&in.Endpoint, &out.Endpoint, s); err != nil {
		return err
	}
	out.Path = in.Path
	out.Authentication = (*AuthenticationOptions)(unsafe.Pointer(in.Authentication))
	out.Headers = *(*[]Header)(unsafe.Pointer(&in.Headers))
	out.TLS = (*OTLPTLS)(unsafe.Pointer(in.TLS))
	return nil
}

// Convert_v1beta1_OTLPOutput_To_v1alpha1_OTLPOutput is an autogenerated conversion function.
func Convert_v1beta1_OTLPOutput_To_v1alpha1_OTLPOutput(in *v1beta1.OTLPOutput, out *OTLPOutput, s conversion.Scope) error {
	return autoConvert_v1beta1_OTLPOutput_To_v1alpha1_OTLPOutput(in, out, s)
}

func autoConvert_v1alpha1_SecretKeyRef_To_v1beta1_SecretKeyRef(in *SecretKeyRef, out *v1beta1.SecretKeyRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_SecretKeyRef_To_v1beta1_SecretKeyRef is an autogenerated conversion function.
func Convert_v1alpha1_SecretKeyRef_To_v1beta1_SecretKeyRef(in *SecretKeyRef, out *v1beta1.SecretKeyRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretKeyRef_To_v1beta1_SecretKeyRef(in, out, s)
}

func autoConvert_v1beta1_SecretKeyRef_To_v1alpha1_SecretKeyRef(in *v1beta1.SecretKeyRef, out *SecretKeyRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_SecretKeyRef_To_v1alpha1_SecretKeyRef is an autogenerated conversion function.
func Convert_v1beta1_SecretKeyRef_To_v1alpha1_SecretKeyRef(in *v1beta1.SecretKeyRef, out *SecretKeyRef, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretKeyRef_To_v1alpha1_SecretKeyRef(in, out, s)
}

func autoConvert_v1alpha1_TracePipeline_To_v1beta1_TracePipeline(in *TracePipeline, out *v1beta1.TracePipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TracePipelineSpec_To_v1beta1_TracePipelineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TracePipelineStatus_To_v1beta1_TracePipelineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TracePipeline_To_v1beta1_TracePipeline is an autogenerated conversion function.
func Convert_v1alpha1_TracePipeline_To_v1beta1_TracePipeline(in *TracePipeline, out *v1beta1.TracePipeline, s conversion.Scope) error {
	return autoConvert_v1alpha1_TracePipeline_To_v1beta1_TracePipeline(in, out, s)
}

func autoConvert_v1beta1_TracePipeline_To_v1alpha1_TracePipeline(in *v1beta1.TracePipeline, out *TracePipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TracePipelineSpec_To_v1alpha1_TracePipelineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TracePipelineStatus_To_v1alpha1_TracePipelineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TracePipeline_To_v1alpha1_TracePipeline is an autogenerated conversion function.
func Convert_v1beta1_TracePipeline_To_v1alpha1_TracePipeline(in *v1beta1.TracePipeline, out *TracePipeline, s conversion.Scope) error {
	return autoConvert_v1beta1_TracePipeline_To_v1alpha1_TracePipeline(in, out, s)
}

func autoConvert_v1alpha1_TracePipelineList_To_v1beta1_TracePipelineList(in *TracePipelineList, out *v1beta1.TracePipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.TracePipeline)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TracePipelineList_To_v1beta1_TracePipelineList is an autogenerated conversion function.
func Convert_v1alpha1_TracePipelineList_To_v1beta1_TracePipelineList(in *TracePipelineList, out *v1beta1.TracePipelineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TracePipelineList_To_v1beta1_TracePipelineList(in, out, s)
}

func autoConvert_v1beta1_TracePipelineList_To_v1alpha1_TracePipelineList(in *v1beta1.TracePipelineList, out *TracePipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TracePipeline)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_TracePipelineList_To_v1alpha1_TracePipelineList is an autogenerated conversion function.
func Convert_v1beta1_TracePipelineList_To_v1alpha1_TracePipelineList(in *v1beta1.TracePipelineList, out *TracePipelineList, s conversion.Scope) error {
	return autoConvert_v1beta1_TracePipelineList_To_v1alpha1_TracePipelineList(in, out, s)
}

func autoConvert_v1alpha1_TracePipelineOutput_To_v1beta1_TracePipelineOutput(in *TracePipelineOutput, out *v1beta1.TracePipelineOutput, s conversion.Scope) error {
	out.OTLP = (*v1beta1.OTLPOutput)(unsafe.Pointer(in.OTLP))
	return nil
}

// Convert_v1alpha1_TracePipelineOutput_To_v1beta1_TracePipelineOutput is an autogenerated conversion function.
func Convert_v1alpha1_TracePipelineOutput_To_v1beta1_TracePipelineOutput(in *TracePipelineOutput, out *v1beta1.TracePipelineOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_TracePipelineOutput_To_v1beta1_TracePipelineOutput(in, out, s)
}

func autoConvert_v1beta1_TracePipelineOutput_To_v1alpha1_TracePipelineOutput(in *v1beta1.TracePipelineOutput, out *TracePipelineOutput, s conversion.Scope) error {
	out.OTLP = (*OTLPOutput)(unsafe.Pointer(in.OTLP))
	return nil
}

// Convert_v1beta1_TracePipelineOutput_To_v1alpha1_TracePipelineOutput is an autogenerated conversion function.
func Convert_v1beta1_TracePipelineOutput_To_v1alpha1_TracePipelineOutput(in *v1beta1.TracePipelineOutput, out *TracePipelineOutput, s conversion.Scope) error {
	return autoConvert_v1beta1_TracePipelineOutput_To_v1alpha1_TracePipelineOutput(in, out, s)
}

func autoConvert_v1alpha1_TracePipelineSpec_To_v1beta1_TracePipelineSpec(in *TracePipelineSpec, out *v1beta1.TracePipelineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_TracePipelineOutput_To_v1beta1_TracePipelineOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	out.Transforms = *(*[]v1beta1.TransformSpec)(unsafe.Pointer(&in.Transforms))
	out.Filters = *(*[]v1beta1.FilterSpec)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1alpha1_TracePipelineSpec_To_v1beta1_TracePipelineSpec is an autogenerated conversion function.
func Convert_v1alpha1_TracePipelineSpec_To_v1beta1_TracePipelineSpec(in *TracePipelineSpec, out *v1beta1.TracePipelineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TracePipelineSpec_To_v1beta1_TracePipelineSpec(in, out, s)
}

func autoConvert_v1beta1_TracePipelineSpec_To_v1alpha1_TracePipelineSpec(in *v1beta1.TracePipelineSpec, out *TracePipelineSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_TracePipelineOutput_To_v1alpha1_TracePipelineOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	out.Transforms = *(*[]TransformSpec)(unsafe.Pointer(&in.Transforms))
	out.Filters = *(*[]FilterSpec)(unsafe.Pointer(&in.Filters))
	return nil
}

// Convert_v1beta1_TracePipelineSpec_To_v1alpha1_TracePipelineSpec is an autogenerated conversion function.
func Convert_v1beta1_TracePipelineSpec_To_v1alpha1_TracePipelineSpec(in *v1beta1.TracePipelineSpec, out *TracePipelineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TracePipelineSpec_To_v1alpha1_TracePipelineSpec(in, out, s)
}

func autoConvert_v1alpha1_TracePipelineStatus_To_v1beta1_TracePipelineStatus(in *TracePipelineStatus, out *v1beta1.TracePipelineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_TracePipelineStatus_To_v1beta1_TracePipelineStatus is an autogenerated conversion function.
func Convert_v1alpha1_TracePipelineStatus_To_v1beta1_TracePipelineStatus(in *TracePipelineStatus, out *v1beta1.TracePipelineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TracePipelineStatus_To_v1beta1_TracePipelineStatus(in, out, s)
}

func autoConvert_v1beta1_TracePipelineStatus_To_v1alpha1_TracePipelineStatus(in *v1beta1.TracePipelineStatus, out *TracePipelineStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_TracePipelineStatus_To_v1alpha1_TracePipelineStatus is an autogenerated conversion function.
func Convert_v1beta1_TracePipelineStatus_To_v1alpha1_TracePipelineStatus(in *v1beta1.TracePipelineStatus, out *TracePipelineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_TracePipelineStatus_To_v1alpha1_TracePipelineStatus(in, out, s)
}

func autoConvert_v1alpha1_TransformSpec_To_v1beta1_TransformSpec(in *TransformSpec, out *v1beta1.TransformSpec, s conversion.Scope) error {
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	out.Statements = *(*[]string)(unsafe.Pointer(&in.Statements))
	return nil
}

// Convert_v1alpha1_TransformSpec_To_v1beta1_TransformSpec is an autogenerated conversion function.
func Convert_v1alpha1_TransformSpec_To_v1beta1_TransformSpec(in *TransformSpec, out *v1beta1.TransformSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TransformSpec_To_v1beta1_TransformSpec(in, out, s)
}

func autoConvert_v1beta1_TransformSpec_To_v1alpha1_TransformSpec(in *v1beta1.TransformSpec, out *TransformSpec, s conversion.Scope) error {
	out.Conditions = *(*[]string)(unsafe.Pointer(&in.Conditions))
	out.Statements = *(*[]string)(unsafe.Pointer(&in.Statements))
	return nil
}

// Convert_v1beta1_TransformSpec_To_v1alpha1_TransformSpec is an autogenerated conversion function.
func Convert_v1beta1_TransformSpec_To_v1alpha1_TransformSpec(in *v1beta1.TransformSpec, out *TransformSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TransformSpec_To_v1alpha1_TransformSpec(in, out, s)
}

func autoConvert_v1alpha1_ValueFromSource_To_v1beta1_ValueFromSource(in *ValueFromSource, out *v1beta1.ValueFromSource, s conversion.Scope) error {
	out.SecretKeyRef = (*v1beta1.SecretKeyRef)(unsafe.Pointer(in.SecretKeyRef))
	return nil
}

// Convert_v1alpha1_ValueFromSource_To_v1beta1_ValueFromSource is an autogenerated conversion function.
func Convert_v1alpha1_ValueFromSource_To_v1beta1_ValueFromSource(in *ValueFromSource, out *v1beta1.ValueFromSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValueFromSource_To_v1beta1_ValueFromSource(in, out, s)
}

func autoConvert_v1beta1_ValueFromSource_To_v1alpha1_ValueFromSource(in *v1beta1.ValueFromSource, out *ValueFromSource, s conversion.Scope) error {
	out.SecretKeyRef = (*SecretKeyRef)(unsafe.Pointer(in.SecretKeyRef))
	return nil
}

// Convert_v1beta1_ValueFromSource_To_v1alpha1_ValueFromSource is an autogenerated conversion function.
func Convert_v1beta1_ValueFromSource_To_v1alpha1_ValueFromSource(in *v1beta1.ValueFromSource, out *ValueFromSource, s conversion.Scope) error {
	return autoConvert_v1beta1_ValueFromSource_To_v1alpha1_ValueFromSource(in, out, s)
}

func autoConvert_v1alpha1_ValueType_To_v1beta1_ValueType(in *ValueType, out *v1beta1.ValueType, s conversion.Scope) error {
	out.Value = in.Value
	out.ValueFrom = (*v1beta1.ValueFromSource)(unsafe.Pointer(in.ValueFrom))
	return nil
}

// Convert_v1alpha1_ValueType_To_v1beta1_ValueType is an autogenerated conversion function.
func Convert_v1alpha1_ValueType_To_v1beta1_ValueType(in *ValueType, out *v1beta1.ValueType, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValueType_To_v1beta1_ValueType(in, out, s)
}

func autoConvert_v1beta1_ValueType_To_v1alpha1_ValueType(in *v1beta1.ValueType, out *ValueType, s conversion.Scope) error {
	out.Value = in.Value
	out.ValueFrom = (*ValueFromSource)(unsafe.Pointer(in.ValueFrom))
	return nil
}

// Convert_v1beta1_ValueType_To_v1alpha1_ValueType is an autogenerated conversion function.
func Convert_v1beta1_ValueType_To_v1alpha1_ValueType(in *v1beta1.ValueType, out *ValueType, s conversion.Scope) error {
	return autoConvert_v1beta1_ValueType_To_v1alpha1_ValueType(in, out, s)
}
