// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewIstioStatusChecker creates a new instance of IstioStatusChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIstioStatusChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *IstioStatusChecker {
	mock := &IstioStatusChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IstioStatusChecker is an autogenerated mock type for the IstioStatusChecker type
type IstioStatusChecker struct {
	mock.Mock
}

type IstioStatusChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *IstioStatusChecker) EXPECT() *IstioStatusChecker_Expecter {
	return &IstioStatusChecker_Expecter{mock: &_m.Mock}
}

// IsIstioActive provides a mock function for the type IstioStatusChecker
func (_mock *IstioStatusChecker) IsIstioActive(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsIstioActive")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IstioStatusChecker_IsIstioActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIstioActive'
type IstioStatusChecker_IsIstioActive_Call struct {
	*mock.Call
}

// IsIstioActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IstioStatusChecker_Expecter) IsIstioActive(ctx interface{}) *IstioStatusChecker_IsIstioActive_Call {
	return &IstioStatusChecker_IsIstioActive_Call{Call: _e.mock.On("IsIstioActive", ctx)}
}

func (_c *IstioStatusChecker_IsIstioActive_Call) Run(run func(ctx context.Context)) *IstioStatusChecker_IsIstioActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IstioStatusChecker_IsIstioActive_Call) Return(b bool, err error) *IstioStatusChecker_IsIstioActive_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *IstioStatusChecker_IsIstioActive_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *IstioStatusChecker_IsIstioActive_Call {
	_c.Call.Return(run)
	return _c
}
