// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kyma-project/telemetry-manager/internal/otelcollector/config/common"
	"github.com/kyma-project/telemetry-manager/internal/otelcollector/config/otlpgateway"
	mock "github.com/stretchr/testify/mock"
)

// NewOTLPGatewayConfigBuilder creates a new instance of OTLPGatewayConfigBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTLPGatewayConfigBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTLPGatewayConfigBuilder {
	mock := &OTLPGatewayConfigBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OTLPGatewayConfigBuilder is an autogenerated mock type for the OTLPGatewayConfigBuilder type
type OTLPGatewayConfigBuilder struct {
	mock.Mock
}

type OTLPGatewayConfigBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *OTLPGatewayConfigBuilder) EXPECT() *OTLPGatewayConfigBuilder_Expecter {
	return &OTLPGatewayConfigBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type OTLPGatewayConfigBuilder
func (_mock *OTLPGatewayConfigBuilder) Build(ctx context.Context, opts otlpgateway.BuildOptions) (*common.Config, common.EnvVars, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *common.Config
	var r1 common.EnvVars
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, otlpgateway.BuildOptions) (*common.Config, common.EnvVars, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, otlpgateway.BuildOptions) *common.Config); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, otlpgateway.BuildOptions) common.EnvVars); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.EnvVars)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, otlpgateway.BuildOptions) error); ok {
		r2 = returnFunc(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OTLPGatewayConfigBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type OTLPGatewayConfigBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - opts otlpgateway.BuildOptions
func (_e *OTLPGatewayConfigBuilder_Expecter) Build(ctx interface{}, opts interface{}) *OTLPGatewayConfigBuilder_Build_Call {
	return &OTLPGatewayConfigBuilder_Build_Call{Call: _e.mock.On("Build", ctx, opts)}
}

func (_c *OTLPGatewayConfigBuilder_Build_Call) Run(run func(ctx context.Context, opts otlpgateway.BuildOptions)) *OTLPGatewayConfigBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 otlpgateway.BuildOptions
		if args[1] != nil {
			arg1 = args[1].(otlpgateway.BuildOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OTLPGatewayConfigBuilder_Build_Call) Return(config *common.Config, envVars common.EnvVars, err error) *OTLPGatewayConfigBuilder_Build_Call {
	_c.Call.Return(config, envVars, err)
	return _c
}

func (_c *OTLPGatewayConfigBuilder_Build_Call) RunAndReturn(run func(ctx context.Context, opts otlpgateway.BuildOptions) (*common.Config, common.EnvVars, error)) *OTLPGatewayConfigBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
