// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/types"
)

// NewProber creates a new instance of Prober. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Prober {
	mock := &Prober{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Prober is an autogenerated mock type for the Prober type
type Prober struct {
	mock.Mock
}

type Prober_Expecter struct {
	mock *mock.Mock
}

func (_m *Prober) EXPECT() *Prober_Expecter {
	return &Prober_Expecter{mock: &_m.Mock}
}

// IsReady provides a mock function for the type Prober
func (_mock *Prober) IsReady(ctx context.Context, name types.NamespacedName) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Prober_IsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReady'
type Prober_IsReady_Call struct {
	*mock.Call
}

// IsReady is a helper method to define mock.On call
//   - ctx context.Context
//   - name types.NamespacedName
func (_e *Prober_Expecter) IsReady(ctx interface{}, name interface{}) *Prober_IsReady_Call {
	return &Prober_IsReady_Call{Call: _e.mock.On("IsReady", ctx, name)}
}

func (_c *Prober_IsReady_Call) Run(run func(ctx context.Context, name types.NamespacedName)) *Prober_IsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.NamespacedName
		if args[1] != nil {
			arg1 = args[1].(types.NamespacedName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Prober_IsReady_Call) Return(err error) *Prober_IsReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Prober_IsReady_Call) RunAndReturn(run func(ctx context.Context, name types.NamespacedName) error) *Prober_IsReady_Call {
	_c.Call.Return(run)
	return _c
}
