apiVersion: telemetry.kyma-project.io/v1beta1
kind: LogPipeline
metadata:
  name: load-test-2
spec:
  input:
    runtime:
      enabled: true
  output:
    http:
      dedot: true
      format: json
      host:
        value: log-receiver.log-load-test
      port: "9880"
      tls:
        insecure: true
        insecureSkipVerify: true
      uri: "/"

---
apiVersion: telemetry.kyma-project.io/v1beta1
kind: LogPipeline
metadata:
  name: load-test-3
spec:
  input:
    runtime:
      enabled: true
  output:
    http:
      dedot: true
      format: json
      host:
        value: log-receiver.log-load-test
      port: "9880"
      tls:
        insecure: true
        insecureSkipVerify: true
      uri: "/"
