// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/kyma-project/telemetry-manager/apis/telemetry/v1alpha1"
	"github.com/kyma-project/telemetry-manager/internal/otelcollector/config/metric/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewAgentConfigBuilder creates a new instance of AgentConfigBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentConfigBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentConfigBuilder {
	mock := &AgentConfigBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AgentConfigBuilder is an autogenerated mock type for the AgentConfigBuilder type
type AgentConfigBuilder struct {
	mock.Mock
}

type AgentConfigBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentConfigBuilder) EXPECT() *AgentConfigBuilder_Expecter {
	return &AgentConfigBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type AgentConfigBuilder
func (_mock *AgentConfigBuilder) Build(pipelines []v1alpha1.MetricPipeline, options agent.BuildOptions) *agent.Config {
	ret := _mock.Called(pipelines, options)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *agent.Config
	if returnFunc, ok := ret.Get(0).(func([]v1alpha1.MetricPipeline, agent.BuildOptions) *agent.Config); ok {
		r0 = returnFunc(pipelines, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.Config)
		}
	}
	return r0
}

// AgentConfigBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type AgentConfigBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - pipelines
//   - options
func (_e *AgentConfigBuilder_Expecter) Build(pipelines interface{}, options interface{}) *AgentConfigBuilder_Build_Call {
	return &AgentConfigBuilder_Build_Call{Call: _e.mock.On("Build", pipelines, options)}
}

func (_c *AgentConfigBuilder_Build_Call) Run(run func(pipelines []v1alpha1.MetricPipeline, options agent.BuildOptions)) *AgentConfigBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]v1alpha1.MetricPipeline), args[1].(agent.BuildOptions))
	})
	return _c
}

func (_c *AgentConfigBuilder_Build_Call) Return(config *agent.Config) *AgentConfigBuilder_Build_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *AgentConfigBuilder_Build_Call) RunAndReturn(run func(pipelines []v1alpha1.MetricPipeline, options agent.BuildOptions) *agent.Config) *AgentConfigBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
