jaeger:
  enabled: true
  resources:
    requests:
      memory: 20Mi
    limits:
      memory: 1Gi
  podLabels:
    sidecar.istio.io/inject: "true"
userconfig:
  service:
    extensions: [jaeger_storage, jaeger_query, healthcheckv2]
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [jaeger_storage_exporter]
    telemetry:
      resource:
        service.name: jaeger
  extensions:
    healthcheckv2:
      use_v2: true
      http:
        endpoint: 0.0.0.0:13133
    jaeger_query:
      base_path: /
      storage:
        traces: memstore
    jaeger_storage:
      backends:
        memstore:
          memory:
            max_traces: 10000
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    jaeger_storage_exporter:
      trace_storage: memstore
