package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"github.com/joho/godotenv"
	"gopkg.in/yaml.v3"
)

const yamlIndent = 2

const (
	envFileName             = ".env"
	secScannersConfigName   = "sec-scanners-config.yaml"
	componentConfigFileName = "component-config.yaml"
	imagesGoRelPath         = "test/testkit/images.go"
)

const (
	moduleName    = "telemetry"
	moduleKind    = "kyma"
	componentName = "kyma-project.io/module/telemetry"
	teamSlug      = "kyma/Huskies"
)

const (
	mendLanguage    = "golang-mod"
	checkmarxPreset = "go-default"
)

var templates = map[string]string{
	imagesGoRelPath: `// This file is generated by "make generate".
// Don't edit, update .env file and run make target generate.

package testkit

const (
	DefaultTelemetryGenImage         = "{{ .ENV_TEST_TELEMETRYGEN_IMAGE }}"
	DefaultOTelCollectorContribImage = "{{ .ENV_TEST_OTEL_COLLECTOR_CONTRIB_IMAGE }}"
	DefaultOTelCollectorImage        = "{{ .ENV_OTEL_COLLECTOR_IMAGE }}"
	SelfMonitorImage                 = "{{ .ENV_SELFMONITOR_IMAGE }}"
	SelfMonitorFIPSImage             = "{{ .ENV_SELFMONITOR_FIPS_IMAGE }}"
	FaultBackendImage                = "{{ .ENV_TEST_FAULT_BACKEND_IMAGE }}"
	AlpineImage                      = "{{ .ENV_TEST_ALPINE_IMAGE }}"
	ChownImage                       = "{{ .ENV_CHOWN_IMAGE }}"
)
`,
}

// prodImageEnvVars lists the .env variables that name images shipped to production.
// Both sec-scanners-config.yaml (BDBA scan) and component-config.yaml (OCM builder)
// must reference exactly this set.
var prodImageEnvVars = []string{
	"ENV_MANAGER_IMAGE",
	"ENV_FLUENTBIT_EXPORTER_IMAGE",
	"ENV_FLUENTBIT_IMAGE",
	"ENV_OTEL_COLLECTOR_IMAGE",
	"ENV_SELFMONITOR_IMAGE",
	"ENV_SELFMONITOR_FIPS_IMAGE",
	"ENV_CHOWN_IMAGE",
}

var scannerExcludes = []string{
	"**/mocks/**",
	"**/stubs/**",
	"**/test/**",
	"**/*_test.go",
	"docs/**",
	"dependencies/populateimages/**",
	"dependencies/sample-app/**",
	"dependencies/stdout-log-generator/**",
	"dependencies/fault-backend/**",
	"internal/tools/**",
	"apis/telemetry/v1alpha1/zz_generated.conversion.go",
}

type secScanConfig struct {
	ModuleName   string       `yaml:"module-name"`
	Kind         string       `yaml:"kind"`
	BDBA         []string     `yaml:"bdba"`
	Mend         mend         `yaml:"mend"`
	CheckmarxOne checkmarxOne `yaml:"checkmarx-one"`
}

type componentConfig struct {
	Name   string   `yaml:"name"`
	Team   string   `yaml:"team"`
	Images []string `yaml:"images"`
}

type mend struct {
	Language string   `yaml:"language"`
	Exclude  []string `yaml:"exclude"`
}

type checkmarxOne struct {
	Preset  string   `yaml:"preset"`
	Exclude []string `yaml:"exclude"`
}

func main() {
	inputDir := flag.String("input-dir", ".", "directory containing the .env file")
	outputDir := flag.String("output-dir", ".", "directory where generated files are written (paths inside are relative to it)")

	flag.Parse()

	if err := run(*inputDir, *outputDir); err != nil {
		log.Fatal(err)
	}
}

func run(inputDir, outputDir string) error {
	envFile := filepath.Join(inputDir, envFileName)

	data, err := godotenv.Read(envFile)
	if err != nil {
		return fmt.Errorf("error reading %s: %w", envFile, err)
	}

	for relPath, tmpl := range templates {
		path := filepath.Join(outputDir, relPath)
		if err := generateFromTemplate(path, tmpl, data); err != nil {
			return fmt.Errorf("error generating file %s: %w", path, err)
		}
	}

	imgs, err := prodImages(data)
	if err != nil {
		return err
	}

	if err := writeYAML(filepath.Join(outputDir, secScannersConfigName), secScanConfig{
		ModuleName:   moduleName,
		Kind:         moduleKind,
		BDBA:         imgs,
		Mend:         mend{Language: mendLanguage, Exclude: scannerExcludes},
		CheckmarxOne: checkmarxOne{Preset: checkmarxPreset, Exclude: scannerExcludes},
	}); err != nil {
		return fmt.Errorf("error generating sec scan config: %w", err)
	}

	if err := writeYAML(filepath.Join(outputDir, componentConfigFileName), componentConfig{
		Name:   componentName,
		Team:   teamSlug,
		Images: imgs,
	}); err != nil {
		return fmt.Errorf("error generating component config: %w", err)
	}

	return nil
}

func prodImages(data map[string]string) ([]string, error) {
	imgs := make([]string, 0, len(prodImageEnvVars))

	for _, key := range prodImageEnvVars {
		val, ok := data[key]
		if !ok || val == "" {
			return nil, fmt.Errorf("env var %s is missing or empty in .env", key)
		}

		imgs = append(imgs, val)
	}

	return imgs, nil
}

func generateFromTemplate(path, tmpl string, data map[string]string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	t := template.Must(template.New("images").Option("missingkey=error").Parse(tmpl))

	return t.Execute(f, data)
}

func writeYAML(path string, v any) error {
	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer file.Close()

	enc := yaml.NewEncoder(file)
	enc.SetIndent(yamlIndent)

	if err := enc.Encode(v); err != nil {
		return fmt.Errorf("encode %s: %w", path, err)
	}

	return nil
}
