name: Build Directory Size Exporter Image

permissions:
  contents: read

on:
  pull_request_target:
    paths:
      - "dependencies/directory-size-exporter/**"
    types: [opened, edited, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths:
      - "dependencies/directory-size-exporter/**"
  workflow_dispatch:

jobs:
  approval:
    uses: ./.github/workflows/approval-gate.yml

  envs:
    needs: [approval]
    if: always() && (needs.approval.result == 'success' || needs.approval.result == 'skipped')
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.create-tags.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Create tags
        id: create-tags
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' || $GITHUB_EVENT_NAME == 'merge_group' ]]; then
            {
              echo "tags<<EOTAGS"
              echo "${{ github.ref_name }}"
              echo "$(git rev-parse --short $GITHUB_SHA)"
              echo "EOTAGS"
            } >> "$GITHUB_OUTPUT"
          else
            {
              echo "tags<<EOTAGS"
              echo "PR-${{ github.event.pull_request.number }}"
              echo "${{ github.event.pull_request.head.sha }}"
              echo "EOTAGS"
            } >> "$GITHUB_OUTPUT"
          fi

  build-image:
    permissions:
      id-token: write # Required for requesting the JWT token
      contents: read
    needs: [ approval, envs ]
    if: ${{ always() && needs.envs.result == 'success' }}
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: directory-size-exporter
      dockerfile: Dockerfile
      context: dependencies/directory-size-exporter
      tags: ${{ needs.envs.outputs.tags }}
      platforms: "linux/amd64,linux/arm64"
