name: Build Self Monitor Image

permissions:
  contents: read

on:
  pull_request_target:
    paths:
      - "dependencies/telemetry-self-monitor/**"
    types: [opened, edited, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths:
      - "dependencies/telemetry-self-monitor/**"
  workflow_dispatch:

jobs:
  approval:
    uses: ./.github/workflows/approval-gate.yml

  envs:
    needs: [approval]
    if: always() && (needs.approval.result == 'success' || needs.approval.result == 'skipped')
    runs-on: ubuntu-latest
    outputs:
      build-args: ${{ steps.prepare-envs.outputs.build-args }}
      tags: ${{ steps.create-tags.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Fetch new env file
        if: github.event_name == 'pull_request_target'
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }} --no-overlay -- dependencies/telemetry-self-monitor/envs

      - name: Prepare Envs
        id: prepare-envs
        run: |
          {
          # this creates a multiline string with the envs.
          # Everything between `build-args<<BUILD_ARGS` and BUILD_ARGS will be content of the build-args variable.
          echo 'build-args<<BUILD_ARGS'
          cat dependencies/telemetry-self-monitor/envs
          echo BUILD_ARGS

          } >> "$GITHUB_OUTPUT"

      - name: load envs into output
        id: load-envs
        run: |
          cat dependencies/telemetry-self-monitor/envs >> "$GITHUB_OUTPUT"

      - name: Get commit short SHA
        id: get-short-sha
        run: echo "short-sha=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT

      - name: Create tags
        id: create-tags
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' || $GITHUB_EVENT_NAME == 'merge_group' ]]; then
            {
              echo "tags<<EOTAGS"
              echo "${{ github.ref_name }}"
              echo "${{ steps.load-envs.outputs.PROMETHEUS_VERSION }}-${{ steps.get-short-sha.outputs.short-sha }}"
              echo "EOTAGS"
            } >> "$GITHUB_OUTPUT"
          else
            {
              echo "tags<<EOTAGS"
              echo "PR-${{ github.event.pull_request.number }}"
              echo "${{ github.event.pull_request.head.sha }}"
              echo "EOTAGS"
            } >> "$GITHUB_OUTPUT"
          fi

  build-image:
    permissions:
      id-token: write # Required for requesting the JWT token
      contents: read
    needs: [ approval, envs ]
    if: ${{ always() && needs.envs.result == 'success' }}
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: tpi/telemetry-self-monitor
      dockerfile: Dockerfile
      context: dependencies/telemetry-self-monitor
      build-args: ${{ needs.envs.outputs.build-args }}
      tags: ${{ needs.envs.outputs.tags }}
      platforms: "linux/amd64,linux/arm64"
