name: PR Code Checks

permissions:
  contents: read

on:
  merge_group:
  pull_request:
    branches:
      - "main"
      - "release-*"
      - "pre-release-*"
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "OWNERS"
      - "CODEOWNERS"
      - "external-images.yaml"
      - ".hyperspace/**"
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Run tests
        run: make test

      - name: Run tests sample-app
        working-directory: dependencies/sample-app
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Run lint
        run: make --debug lint

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Run coverage check
        run: make check-coverage

  verify-code-generated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Verify all code and manifests were generated and committed
        run: make check-clean

  test-renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Test Renovate config
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
  
  verify-runtime-additional-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Verify runtime additional metrics
        run: ./hack/verify-runtime-additional-metrics.sh
