name: PR Docu Checks

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths:
      - "docs/**"
      - "**/*.md"
      - "apis/**"
      - "webhook/**"
      - "config/**"
      - "helm/**"
      - ".github/workflows/pr-docu-checks.yml"
  workflow_dispatch:

jobs:
  verify-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Verify manifests
        run: make crd-docs-gen manifests-experimental check-clean

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "24.x"
      - name: Install markdown link checker
        run: npm install -g md-check-link
      - name: Verify links
        run: |
          md-check-link -q -n 8 -c https://raw.githubusercontent.com/kyma-project/md-check-link/main/.mlc.config.json ./
