name: PR Helm Checks

permissions:
  contents: read

on:
  merge_group:
  pull_request:
    branches:
      - "main"
      - "release-*"
      - "pre-release-*"
    paths:
      - "helm/**"
      - ".github/workflows/pr-helm-checks.yml"
  workflow_dispatch:

jobs:
  helm-kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Validate Helm templates with kubeconform
        run: make check-kubeconform
