name: Check Release Branch

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "release-*"
jobs:
  validate-envs:
    name: Validate helm/values.yaml and sec-scanners-config.yaml files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Verify helm/values.yaml file has no main branch references
        run: |
          if grep -q "main" helm/values.yaml; then
            echo "The helm/values.yaml file contains references to the main branch"
            exit 1
          fi

      - name: Verify sec-scanners-config.yaml file has no main branch references
        run: |
          if grep -q "main" sec-scanners-config.yaml; then
            echo "The sec-scanners-config.yaml file contains references to the main branch"
            exit 1
          fi
